/*
Copyright (C) 2026 Thomas Jones <me@thomasjones.id.au>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

#ifndef ENGINE_FIELDS_H
#define ENGINE_FIELDS_H

/*
 * The engine structs' Python surface, as X-macro lists. Each list is expanded three times
 * in python_objects.c: to emit the accessors, to build the PyGetSetDef table, and to assert
 * the field's byte offset.
 *
 * Columns are:
 *
 *   KIND   one of the QLX_GETSET_* / QLX_GET_* field kinds in python_objects.c
 *   FIELD  the C member, spelled exactly as in quake_common.h
 *   NAME   the Python attribute, snake_case
 *   OFF    the member's byte offset, asserted at compile time
 *   DOC    prose for help(), or NULL to fall back to naming the C field
 *
 * OFF is generated by tools/gen_field_offsets.py and guards against regressions only, since
 * it comes from the same header it checks. quake_common.h's disassembly-derived assertions
 * are what pin the structs to the binary; leave those alone.
 *
 * Left out of LEVEL_FIELDS: clients and gentities (duplicates of level->clients and
 * g_entities; use GameClient(n) and Entity(n)), spawnVars, intermissionMap* and logFile.
 */

// clang-format off

/* roundState_t. Reached as minqlxtended.level.round. */
#define ROUNDSTATE_FIELDS(X)                                                                       \
    X(INT,  eCurrent,             current,                  0, "The round state right now; one of the ROUND_* constants.") \
    X(INT,  eNext,                next,                     4, "The state it moves to at time_next.") \
    X(INT,  tNext,                time_next,                8, NULL)                               \
    X(INT,  startTime,            start_time,              12, "Level time the current state began, rather than the round.") \
    X(INT,  turn,                 turn,                    16, "Attack & Defend only: which side is attacking this round.") \
    X(INT,  round,                round,                   20, NULL)                               \
    X(INT,  prevRoundWinningTeam, prev_round_winning_team, 24, "Freeze Tag only. Despite the name, no other gametype writes it, so it is not a round winner.") \
    X(BOOL, touch,                touch,                   28, NULL)                               \
    X(BOOL, capture,              capture,                 32, NULL)

/* level_locals_t. Reached as minqlxtended.level. */
#define LEVEL_FIELDS(X)                                                                            \
    X(INT,     gentitySize,                          gentity_size,                             16, NULL) \
    X(INT,     num_entities,                         num_entities,                             20, "High-water mark of the entity array, which sits above the live count.") \
    X(INT,     warmupTime,                           warmup_time,                              24, "Level time warmup ends; -1 while waiting on players, 0 outside warmup.") \
    X(INT,     maxclients,                           maxclients,                               32, NULL) \
    X(INT,     time,                                 time,                                     36, "Level time in milliseconds. Stops advancing while the game is paused.") \
    X(INT,     frametime,                            frametime,                                40, "Milliseconds the last frame covered.") \
    X(INT,     startTime,                            start_time,                               44, NULL) \
    X(INTARR,  teamScores,                           team_scores,                              48, "Score per team, indexed by the TEAM_* constants.") \
    X(INT,     nextTeamInfoTime,                     next_team_info_time,                      64, NULL) \
    X(BOOL,    newSession,                           new_session,                              68, NULL) \
    X(BOOL,    restarted,                            restarted,                                72, NULL) \
    X(BOOL,    shufflePending,                       shuffle_pending,                          76, NULL) \
    X(INT,     shuffleReadyTime,                     shuffle_ready_time,                       80, NULL) \
    X(INT,     numConnectedClients,                  num_connected_clients,                    84, NULL) \
    X(INT,     numNonSpectatorClients,               num_non_spectator_clients,                88, NULL) \
    X(INT,     numPlayingClients,                    num_playing_clients,                      92, NULL) \
    X(INT,     numReadyClients,                      num_ready_clients,                        96, NULL) \
    X(INT,     numReadyHumans,                       num_ready_humans,                        100, NULL) \
    X(INT,     numStandardClients,                   num_standard_clients,                    104, NULL) \
    X(INTARR,  sortedClients,                        sorted_clients,                          108, "Client ids in scoreboard order. Only the first num_connected_clients entries mean anything.") \
    X(INT,     follow1,                              follow1,                                 364, NULL) \
    X(INT,     follow2,                              follow2,                                 368, NULL) \
    X(INT,     snd_fry,                              snd_fry,                                 372, NULL) \
    X(INT,     warmupModificationCount,              warmup_modification_count,               376, NULL) \
    X(CHARBUF, voteString,                           vote_string,                             380, "The command a passing vote will run.") \
    X(CHARBUF, voteDisplayString,                    vote_display_string,                    1404, "What players are shown they are voting on.") \
    X(INT,     voteExecuteTime,                      vote_execute_time,                      2428, "Level time the passed vote runs at; 0 when no vote is pending execution.") \
    X(INT,     voteTime,                             vote_time,                              2432, "Level time the current vote started; 0 when no vote is running.") \
    X(INT,     voteYes,                              vote_yes,                               2436, NULL) \
    X(INT,     voteNo,                               vote_no,                                2440, NULL) \
    X(INT,     pendingVoteCaller,                    pending_vote_caller,                    2444, "Client id that called the current vote, or -1.") \
    X(BOOL,    spawning,                             spawning,                               2448, NULL) \
    X(INT,     numSpawnVars,                         num_spawn_vars,                         2452, NULL) \
    X(INT,     numSpawnVarChars,                     num_spawn_var_chars,                    3480, NULL) \
    X(INT,     intermissionQueued,                   intermission_queued,                    7580, "Level time intermission was queued; 0 when it has not been. The game_end event watches this.") \
    X(INT,     intermissionTime,                     intermission_time,                      7584, NULL) \
    X(BOOL,    readyToExit,                          ready_to_exit,                          7588, NULL) \
    X(BOOL,    votingEnded,                          voting_ended,                           7592, NULL) \
    X(INT,     exitTime,                             exit_time,                              7596, NULL) \
    X(VEC3,    intermission_origin,                  intermission_origin,                    7600, NULL) \
    X(VEC3,    intermission_angle,                   intermission_angle,                     7612, NULL) \
    X(BOOL,    locationLinked,                       location_linked,                        7624, NULL) \
    X(ENTREF,  locationHead,                         location_head,                          7632, "Head of the map's location list, or None.") \
    X(INT,     timePauseBegin,                       time_pause_begin,                       7640, "Level time the game was paused at; 0 when it is not paused.") \
    X(INT,     timeOvertime,                         time_overtime,                          7644, NULL) \
    X(INT,     timeInitialKeySpawn,                  time_initial_key_spawn,                 7648, NULL) \
    X(INT,     timeInitialPowerupSpawn,              time_initial_powerup_spawn,             7652, NULL) \
    X(INT,     bodyQueIndex,                         body_que_index,                         7656, NULL) \
    X(ENTREFARR, bodyQue,                            body_que,                               7664, "The corpse queue. Read-only.") \
    X(INT,     portalSequence,                       portal_sequence,                        7728, NULL) \
    X(BOOL,    gameStatsReported,                    game_stats_reported,                    7732, NULL) \
    X(BOOL,    mapIsTrainingMap,                     map_is_training_map,                    7736, "The read side of allow_single_player().") \
    X(INT,     clientNum1stPlayer,                   client_num_1st_player,                  7740, NULL) \
    X(INT,     clientNum2ndPlayer,                   client_num_2nd_player,                  7744, NULL) \
    X(CHARBUF, scoreboardArchive1,                   scoreboard_archive1,                    7748, NULL) \
    X(CHARBUF, scoreboardArchive2,                   scoreboard_archive2,                    8772, NULL) \
    X(CHARBUF, firstScorer,                          first_scorer,                           9796, NULL) \
    X(CHARBUF, lastScorer,                           last_scorer,                            9836, NULL) \
    X(CHARBUF, lastTeamScorer,                       last_team_scorer,                       9876, NULL) \
    X(CHARBUF, firstFrag,                            first_frag,                             9916, NULL) \
    X(VEC3,    red_flag_origin,                      red_flag_origin,                        9956, NULL) \
    X(VEC3,    blue_flag_origin,                     blue_flag_origin,                       9968, NULL) \
    X(INTARR,  spawnCount,                           spawn_count,                            9980, NULL) \
    X(INTARR,  runeSpawns,                           rune_spawns,                            9996, NULL) \
    X(INTARR,  itemCount,                            item_count,                            10016, NULL) \
    X(INT,     suddenDeathRespawnDelay,              sudden_death_respawn_delay,            10256, NULL) \
    X(INT,     suddenDeathRespawnDelayLastAnnounced, sudden_death_respawn_delay_last_announced, 10260, NULL) \
    X(INTARR,  numRedArmorPickups,                   num_red_armor_pickups,                 10264, "Per team, indexed by the TEAM_* constants.") \
    X(INTARR,  numYellowArmorPickups,                num_yellow_armor_pickups,              10280, NULL) \
    X(INTARR,  numGreenArmorPickups,                 num_green_armor_pickups,               10296, NULL) \
    X(INTARR,  numMegaHealthPickups,                 num_mega_health_pickups,               10312, NULL) \
    X(INTARR,  numQuadDamagePickups,                 num_quad_damage_pickups,               10328, NULL) \
    X(INTARR,  numBattleSuitPickups,                 num_battle_suit_pickups,               10344, NULL) \
    X(INTARR,  numRegenerationPickups,               num_regeneration_pickups,              10360, NULL) \
    X(INTARR,  numHastePickups,                      num_haste_pickups,                     10376, NULL) \
    X(INTARR,  numInvisibilityPickups,               num_invisibility_pickups,              10392, NULL) \
    X(INTARR,  quadDamagePossessionTime,             quad_damage_possession_time,           10408, NULL) \
    X(INTARR,  battleSuitPossessionTime,             battle_suit_possession_time,           10424, NULL) \
    X(INTARR,  regenerationPossessionTime,           regeneration_possession_time,          10440, NULL) \
    X(INTARR,  hastePossessionTime,                  haste_possession_time,                 10456, NULL) \
    X(INTARR,  invisibilityPossessionTime,           invisibility_possession_time,          10472, NULL) \
    X(INTARR,  numFlagPickups,                       num_flag_pickups,                      10488, NULL) \
    X(INTARR,  numMedkitPickups,                     num_medkit_pickups,                    10504, NULL) \
    X(INTARR,  flagPossessionTime,                   flag_possession_time,                  10520, NULL) \
    X(ENTREFARR, dominationPoints,                   domination_points,                     10536, "Domination control points. Read-only.") \
    X(INT,     dominationPointCount,                 domination_point_count,                10576, NULL) \
    X(INT,     dominationPointsTallied,              domination_points_tallied,             10580, NULL) \
    X(INT,     racePointCount,                       race_point_count,                      10584, NULL) \
    X(BOOL,    disableDropWeapon,                    disable_drop_weapon,                   10588, NULL) \
    X(BOOL,    teamShuffleActive,                    team_shuffle_active,                   10592, NULL) \
    X(INTARR,  lastTeamScores,                       last_team_scores,                      10596, NULL) \
    X(INTARR,  lastTeamRoundScores,                  last_team_round_scores,                10612, NULL) \
    X(INT,     attackingTeam,                        attacking_team,                        10628, "Attack & Defend and one-flag CTF: which team is attacking.") \
    X(INT,     lastTeamCountSent,                    last_team_count_sent,                  10668, NULL) \
    X(INT,     infectedConscript,                    infected_conscript,                    10672, NULL) \
    X(INT,     lastZombieSurvivor,                   last_zombie_survivor,                  10676, NULL) \
    X(INT,     zombieScoreTime,                      zombie_score_time,                     10680, NULL) \
    X(INT,     lastInfectionTime,                    last_infection_time,                   10684, NULL) \
    X(INTARR,  intermissionMapVotes,                 intermission_map_votes,                19904, NULL) \
    X(BOOL,    matchForfeited,                       match_forfeited,                       19916, "Set when the match ended without a result. The game_end event reports it.") \
    X(INT,     allReadyTime,                         all_ready_time,                        19920, NULL) \
    X(BOOL,    notifyCvarChange,                     notify_cvar_change,                    19924, NULL) \
    X(INT,     notifyCvarChangeTime,                 notify_cvar_change_time,               19928, NULL) \
    X(INT,     lastLeadChangeTime,                   last_lead_change_time,                 19932, NULL) \
    X(INT,     lastLeadChangeClient,                 last_lead_change_client,               19936, "CalculateRanks writes -1 at match start, then the leading client's id in FFA and duel, or 0 for red and 1 for blue in the team-score gametypes. Not a client id in a team game.") \
    X(INT,     lastLeadChangeElapsedTime,            last_lead_change_elapsed_time,         19940, NULL)

/*
 * minqlxtended.match_state has no list here: the match-play state is six separate globals,
 * so there is no struct to generate from. It is hand-written in python_objects.c.
 */

/*
 * entityState_t. Reached as Entity(n).s. The two trajectory_t members are flattened and
 * written out twice: gen_field_offsets.py needs every row textually present.
 */
#define ENTITYSTATE_FIELDS(X)                                                                      \
    X(INT,  number,          number,            0, "The entity's own index.")                      \
    X(INT,  eType,           e_type,            4, "One of the ET_* constants.")                   \
    X(INT,  eFlags,          e_flags,           8, "An EF_* bitfield.")                            \
    X(INT,   pos.trType,     pos_type,         12, "One of the TR_* constants.")                   \
    X(INT,   pos.trTime,     pos_time,         16, NULL)                                           \
    X(INT,   pos.trDuration, pos_duration,     20, NULL)                                           \
    X(VEC3,  pos.trBase,     pos_base,         24, NULL)                                           \
    X(VEC3,  pos.trDelta,    pos_delta,        36, NULL)                                           \
    X(FLOAT, pos.gravity,    pos_gravity,      48, "Only used by TR_CUSTOM_GRAVITY.")              \
    X(INT,   apos.trType,    apos_type,        52, "One of the TR_* constants.")                   \
    X(INT,   apos.trTime,    apos_time,        56, NULL)                                           \
    X(INT,   apos.trDuration, apos_duration,   60, NULL)                                           \
    X(VEC3,  apos.trBase,    apos_base,        64, NULL)                                           \
    X(VEC3,  apos.trDelta,   apos_delta,       76, NULL)                                           \
    X(FLOAT, apos.gravity,   apos_gravity,     88, "Only used by TR_CUSTOM_GRAVITY.")              \
    X(INT,  time,            time,             92, NULL)                                           \
    X(INT,  time2,           time2,            96, NULL)                                           \
    X(VEC3, origin,          origin,          100, NULL)                                           \
    X(VEC3, origin2,         origin2,         112, NULL)                                           \
    X(VEC3, angles,          angles,          124, NULL)                                           \
    X(VEC3, angles2,         angles2,         136, NULL)                                           \
    X(INT,  otherEntityNum,  other_entity_num,148, NULL)                                           \
    X(INT,  otherEntityNum2, other_entity_num2, 152, NULL)                                           \
    X(INT,  groundEntityNum, ground_entity_num, 156, NULL)                                           \
    X(INT,  constantLight,   constant_light,  160, NULL)                                           \
    X(INT,  loopSound,       loop_sound,      164, NULL)                                           \
    X(INT,  modelindex,      modelindex,      168, NULL)                                           \
    X(INT,  modelindex2,     modelindex2,     172, NULL)                                           \
    X(INT,  clientNum,       client_num,      176, NULL)                                           \
    X(INT,  frame,           frame,           180, NULL)                                           \
    X(INT,  solid,           solid,           184, NULL)                                           \
    X(INT,  event,           event,           188, NULL)                                           \
    X(INT,  eventParm,       event_parm,      192, NULL)                                           \
    X(INT,  powerups,        powerups,        196, "A bitfield here; ps.powerups holds the timers.") \
    X(INT,  health,          health,          200, NULL)                                           \
    X(INT,  armor,           armor,           204, NULL)                                           \
    X(INT,  weapon,          weapon,          208, NULL)                                           \
    X(INT,  location,        location,        212, NULL)                                           \
    X(INT,  legsAnim,        legs_anim,       216, NULL)                                           \
    X(INT,  torsoAnim,       torso_anim,      220, NULL)                                           \
    X(INT,  generic1,        generic1,        224, NULL)                                           \
    X(INT,  jumpTime,        jump_time,       228, NULL)                                           \
    X(INT,  doubleJumped,    double_jumped,   232, NULL)

/* entityShared_t. Reached as Entity(n).r. */
#define ENTITYSHARED_FIELDS(X)                                                                     \
    X(BOOL, linked,        linked,       236, "Whether the entity is in the world's area grid.")   \
    X(INT,  linkcount,     linkcount,    240, NULL)                                                \
    X(INT,  svFlags,       sv_flags,     244, "An SVF_* bitfield. SVF_BOT is how you tell a bot from a human.") \
    X(INT,  singleClient,  single_client,248, NULL)                                                \
    X(BOOL, bmodel,        bmodel,       252, NULL)                                                \
    X(VEC3, mins,          mins,         256, NULL)                                                \
    X(VEC3, maxs,          maxs,         268, NULL)                                                \
    X(INT,  contents,      contents,     280, NULL)                                                \
    X(VEC3, absmin,        absmin,       284, NULL)                                                \
    X(VEC3, absmax,        absmax,       296, NULL)                                                \
    X(VEC3, currentOrigin, current_origin, 308, "Where the entity actually is, as opposed to s.origin.") \
    X(VEC3, currentAngles, current_angles, 320, NULL)                                                \
    X(INT,  ownerNum,      owner_num,    332, "Entity that owns this one; a missile points at whoever fired it.")

/*
 * gentity_t. Reached as Entity(n). s and r are sub-objects, client returns a GameClient,
 * and every char* member is read-only: writing one would mean an allocation with no owner.
 */
#define ENTITY_FIELDS(X)                                                                           \
    X(BOOL,    inuse,                   inuse,                 584, "False for a freed slot. Reading most other fields off one is meaningless.") \
    X(CHARPTR, classname,               classname,             592, "Read-only. G_FreeEntity does not clear it, so a freed slot keeps a stale one.") \
    X(INT,     spawnflags,              spawnflags,            600, NULL)                          \
    X(BOOL,    neverFree,               never_free,            604, NULL)                          \
    X(INT,     flags,                   flags,                 608, "An FL_* bitfield; FL_GODMODE and FL_NOTARGET live here.") \
    X(CHARPTR, model,                   model,                 616, NULL)                          \
    X(CHARPTR, model2,                  model2,                624, NULL)                          \
    X(INT,     freetime,                freetime,              632, NULL)                          \
    X(INT,     eventTime,               event_time,            636, NULL)                          \
    X(BOOL,    freeAfterEvent,          free_after_event,      640, NULL)                          \
    X(BOOL,    unlinkAfterEvent,        unlink_after_event,    644, NULL)                          \
    X(BOOL,    physicsObject,           physics_object,        648, NULL)                          \
    X(FLOAT,   physicsBounce,           physics_bounce,        652, NULL)                          \
    X(INT,     clipmask,                clipmask,              656, NULL)                          \
    X(INT,     moverState,              mover_state,           660, "One of the MOVER_* constants.") \
    X(INT,     soundPos1,               sound_pos1,            664, NULL)                          \
    X(INT,     sound1to2,               sound1to2,             668, NULL)                          \
    X(INT,     sound2to1,               sound2to1,             672, NULL)                          \
    X(INT,     soundPos2,               sound_pos2,            676, NULL)                          \
    X(INT,     soundLoop,               sound_loop,            680, NULL)                          \
    X(ENTREF,  parent,                  parent,                688, NULL)                          \
    X(ENTREF,  nextTrain,               next_train,            696, NULL)                          \
    X(ENTREF,  prevTrain,               prev_train,            704, NULL)                          \
    X(VEC3,    pos1,                    pos1,                  712, NULL)                          \
    X(VEC3,    pos2,                    pos2,                  724, NULL)                          \
    X(CHARPTR, message,                 message,               736, NULL)                          \
    X(CHARPTR, cvar,                    cvar,                  744, NULL)                          \
    X(CHARPTR, tourPointTarget,         tour_point_target,     752, NULL)                          \
    X(CHARPTR, tourPointTargetName,     tour_point_target_name,760, NULL)                          \
    X(CHARPTR, noise,                   noise,                 768, NULL)                          \
    X(INT,     timestamp,               timestamp,             776, NULL)                          \
    X(FLOAT,   angle,                   angle,                 780, NULL)                          \
    X(CHARPTR, target,                  target,                784, "The map's entity graph: what this entity fires when triggered.") \
    X(CHARPTR, targetname,              targetname,            792, "What other entities name to target this one.") \
    X(CHARPTR, targetShaderName,        target_shader_name,    800, NULL)                          \
    X(CHARPTR, targetShaderNewName,     target_shader_new_name,808, NULL)                          \
    X(ENTREF,  target_ent,              target_ent,            816, NULL)                          \
    X(FLOAT,   speed,                   speed,                 824, NULL)                          \
    X(VEC3,    movedir,                 movedir,               828, NULL)                          \
    X(INT,     nextthink,               nextthink,             840, "Level time this entity next runs its think. 0 disables it.") \
    X(FNPTR,   think,                   think,                 848, NULL)                          \
    X(FNPTR,   framethink,              framethink,            856, NULL)                          \
    X(FNPTR,   reached,                 reached,               864, NULL)                          \
    X(FNPTR,   blocked,                 blocked,               872, NULL)                          \
    X(FNPTR,   touch,                   touch,                 880, NULL)                          \
    X(FNPTR,   use,                     use,                   888, NULL)                          \
    X(FNPTR,   pain,                    pain,                  896, NULL)                          \
    X(FNPTR,   die,                     die,                   904, NULL)                          \
    X(INT,     pain_debounce_time,      pain_debounce_time,    912, NULL)                          \
    X(INT,     fly_sound_debounce_time, fly_sound_debounce_time, 916, NULL)                          \
    X(INT,     health,                  health,                920, "The authoritative health. Not stats[STAT_HEALTH], which is clamped for the HUD.") \
    X(BOOL,    takedamage,              takedamage,            924, NULL)                          \
    X(INT,     damage,                  damage,                928, NULL)                          \
    X(INT,     damageFactor,            damage_factor,         932, NULL)                          \
    X(INT,     splashDamage,            splash_damage,         936, NULL)                          \
    X(INT,     splashRadius,            splash_radius,         940, NULL)                          \
    X(INT,     methodOfDeath,           method_of_death,       944, NULL)                          \
    X(INT,     splashMethodOfDeath,     splash_method_of_death,948, NULL)                          \
    X(INT,     count,                   count,                 952, NULL)                          \
    X(ENTREF,  enemy,                   enemy,                 960, NULL)                          \
    X(ENTREF,  activator,               activator,             968, NULL)                          \
    X(CHARPTR, team,                    team,                  976, "The map's entity team string, unrelated to the TEAM_* values.") \
    X(ENTREF,  teammaster,              teammaster,            984, NULL)                          \
    X(ENTREF,  teamchain,               teamchain,             992, NULL)                          \
    X(INT,     kamikazeTime,            kamikaze_time,        1000, NULL)                          \
    X(INT,     kamikazeShockTime,       kamikaze_shock_time,  1004, NULL)                          \
    X(INT,     watertype,               watertype,            1008, NULL)                          \
    X(INT,     waterlevel,              waterlevel,           1012, NULL)                          \
    X(INT,     noise_index,             noise_index,          1016, NULL)                          \
    X(INT,     bouncecount,             bouncecount,          1020, NULL)                          \
    X(FLOAT,   wait,                    wait,                 1024, "Item respawn time, among other uses.") \
    X(FLOAT,   random,                  random,               1028, NULL)                          \
    X(INT,     spawnTime,               spawn_time,           1032, NULL)                          \
    X(INT,     pickupCount,             pickup_count,         1048, "Bumped once per successful pickup; the item_pickup event diffs it.")

/* playerState_t. Reached as GameClient(n).ps. */
#define PLAYERSTATE_FIELDS(X)                                                                      \
    X(INT,    commandTime,         command_time,           0, NULL)                                \
    X(INT,    pm_type,             pm_type,                4, "One of the PM_* constants. PM_NORMAL is alive, PM_DEAD is not.") \
    X(INT,    bobCycle,            bob_cycle,              8, NULL)                                \
    X(INT,    pm_flags,            pm_flags,              12, "A PMF_* bitfield: ducked, frozen, following, scoreboard, and so on.") \
    X(INT,    pm_time,             pm_time,               16, NULL)                                \
    X(VEC3,   origin,              origin,                20, NULL)                                \
    X(VEC3,   velocity,            velocity,              32, NULL)                                \
    X(INT,    weaponTime,          weapon_time,           44, NULL)                                \
    X(INT,    gravity,             gravity,               48, NULL)                                \
    X(INT,    speed,               speed,                 52, NULL)                                \
    X(INTARR, delta_angles,        delta_angles,          56, NULL)                                \
    X(INT,    groundEntityNum,     ground_entity_num,     68, NULL)                                \
    X(INT,    legsTimer,           legs_timer,            72, NULL)                                \
    X(INT,    legsAnim,            legs_anim,             76, NULL)                                \
    X(INT,    torsoTimer,          torso_timer,           80, NULL)                                \
    X(INT,    torsoAnim,           torso_anim,            84, NULL)                                \
    X(INT,    movementDir,         movement_dir,          88, NULL)                                \
    X(VEC3,   grapplePoint,        grapple_point,         92, NULL)                                \
    X(INT,    eFlags,              e_flags,              104, "An EF_* bitfield: EF_DEAD, EF_TALK, EF_VOTED, the award flags.") \
    X(INT,    eventSequence,       event_sequence,       108, NULL)                                \
    X(INTARR, events,              events,               112, NULL)                                \
    X(INTARR, eventParms,          event_parms,          120, NULL)                                \
    X(INT,    externalEvent,       external_event,       128, NULL)                                \
    X(INT,    externalEventParm,   external_event_parm,  132, NULL)                                \
    X(INT,    clientNum,           client_num,           136, NULL)                                \
    X(INT,    location,            location,             140, "Index into the map's location list; what the loc reporting uses.") \
    X(INT,    weapon,              weapon,               144, NULL)                                \
    X(INT,    weaponPrimary,       weapon_primary,       148, NULL)                                \
    X(INT,    weaponstate,         weaponstate,          152, NULL)                                \
    X(INT,    fov,                 fov,                  156, NULL)                                \
    X(VEC3,   viewangles,          viewangles,           160, "Where the player is looking.")      \
    X(INT,    viewheight,          viewheight,           172, NULL)                                \
    X(INT,    damageEvent,         damage_event,         176, NULL)                                \
    X(INT,    damageYaw,           damage_yaw,           180, NULL)                                \
    X(INT,    damagePitch,         damage_pitch,         184, NULL)                                \
    X(INT,    damageCount,         damage_count,         188, NULL)                                \
    X(INTARR, stats,               stats,                192, "Indexed by the STAT_* constants.")  \
    X(INTARR, persistant,          persistant,           256, "Indexed by the PERS_* constants; the medal counters live here.") \
    X(INTARR, powerups,            powerups,             320, "Expiry times, indexed by the PW_* constants. 0 means not held.") \
    X(INTARR, ammo,                ammo,                 384, "Indexed by the WP_* constants.")    \
    X(INT,    generic1,            generic1,             448, NULL)                                \
    X(INT,    loopSound,           loop_sound,           452, NULL)                                \
    X(INT,    jumppad_ent,         jumppad_ent,          456, NULL)                                \
    X(INT,    jumpTime,            jump_time,            460, NULL)                                \
    X(INT,    doubleJumped,        double_jumped,        464, NULL)                                \
    X(INT,    crouchTime,          crouch_time,          468, NULL)                                \
    X(INT,    crouchSlideTime,     crouch_slide_time,    472, NULL)                                \
    X(SCHAR,  forwardmove,         forwardmove,          476, "Live movement input, -127 to 127.") \
    X(SCHAR,  rightmove,           rightmove,            477, NULL)                                \
    X(SCHAR,  upmove,              upmove,               478, NULL)                                \
    X(INT,    ping,                ping,                 480, "The game module's copy. Client.ping is the server's own.") \
    X(INT,    pmove_framecount,    pmove_framecount,     484, NULL)                                \
    X(INT,    jumppad_frame,       jumppad_frame,        488, NULL)                                \
    X(INT,    entityEventSequence, entity_event_sequence,492, NULL)                                \
    X(INT,    freezetime,          freezetime,           496, NULL)                                \
    X(INT,    thawtime,            thawtime,             500, NULL)                                \
    X(INT,    thawClientNum_valid, thaw_client_num_valid,504, NULL)                                \
    X(INT,    thawClientNum,       thaw_client_num,      508, NULL)                                \
    X(INT,    respawnTime,         respawn_time,         512, NULL)                                \
    X(INTARR, localPersistant,     local_persistant,     516, NULL)                                \
    X(INT,    roundDamage,         round_damage,         580, NULL)                                \
    X(INT,    roundShots,          round_shots,          584, NULL)                                \
    X(INT,    roundHits,           round_hits,           588, NULL)

/* playerTeamState_t. Reached as GameClient(n).pers.team_state. */
#define TEAMSTATE_FIELDS(X)                                                                        \
    X(INT, state,              state,                0, NULL)                                      \
    X(INT, captures,           captures,             4, NULL)                                      \
    X(INT, basedefense,        basedefense,          8, NULL)                                      \
    X(INT, carrierdefense,     carrierdefense,      12, NULL)                                      \
    X(INT, flagrecovery,       flagrecovery,        16, NULL)                                      \
    X(INT, fragcarrier,        fragcarrier,         20, NULL)                                      \
    X(INT, assists,            assists,             24, NULL)                                      \
    X(INT, flagruntime,        flagruntime,         28, NULL)                                      \
    X(INT, flagrunrelays,      flagrunrelays,       32, NULL)                                      \
    X(INT, lasthurtcarrier,    lasthurtcarrier,     36, NULL)                                      \
    X(INT, lastreturnedflag,   lastreturnedflag,    40, NULL)                                      \
    X(INT, lastfraggedcarrier, lastfraggedcarrier,  44, NULL)

/*
 * clientPersistant_t. Reached as GameClient(n).pers. The usercmd_t is flattened onto it as
 * cmd_*, as entityState_t's trajectories are.
 */
#define PERSISTANT_FIELDS(X)                                                                       \
    X(INT,     connected,                connected,                  0, "One of the CON_* constants.") \
    X(INT,     cmd.serverTime,           cmd_server_time,            4, NULL)                      \
    X(INTARR,  cmd.angles,               cmd_angles,                 8, NULL)                      \
    X(INT,     cmd.buttons,              cmd_buttons,               20, "The player's live button state.") \
    X(BYTE,    cmd.weapon,               cmd_weapon,                24, NULL)                      \
    X(BYTE,    cmd.weaponPrimary,        cmd_weapon_primary,        25, NULL)                      \
    X(BYTE,    cmd.fov,                  cmd_fov,                   26, NULL)                      \
    X(SCHAR,   cmd.forwardmove,          cmd_forwardmove,           27, NULL)                      \
    X(SCHAR,   cmd.rightmove,            cmd_rightmove,             28, NULL)                      \
    X(SCHAR,   cmd.upmove,               cmd_upmove,                29, NULL)                      \
    X(BYTE,    cmd.doubleTap,            cmd_double_tap,            30, NULL)                      \
    X(BOOL,    localClient,              local_client,              32, NULL)                      \
    X(BOOL,    initialSpawn,             initial_spawn,             36, NULL)                      \
    X(BOOL,    predictItemPickup,        predict_item_pickup,       40, NULL)                      \
    X(CHARBUF, netname,                  netname,                   44, "The name PlayerInfo reports.") \
    X(CHARBUF, country,                  country,                   84, "The engine's own copy, as opposed to the userinfo cvar.") \
    X(U64,     steamId,                  steam_id,                 112, NULL)                      \
    X(INT,     maxHealth,                max_health,               120, NULL)                      \
    X(INT,     voteCount,                vote_count,               124, NULL)                      \
    X(INT,     voteState,                vote_state,               128, "The read side of force_vote(); one of the VOTE_* constants.") \
    X(INT,     complaints,               complaints,               132, NULL)                      \
    X(INT,     complaintClient,          complaint_client,         136, NULL)                      \
    X(INT,     complaintEndTime,         complaint_end_time,       140, NULL)                      \
    X(INT,     damageFromTeammates,      damage_from_teammates,    144, NULL)                      \
    X(INT,     damageToTeammates,        damage_to_teammates,      148, NULL)                      \
    X(BOOL,    ready,                    ready,                    152, "Warmup ready state, without scraping a configstring for it.") \
    X(INT,     autoaction,               autoaction,               156, NULL)                      \
    X(INT,     timeouts,                 timeouts,                 160, NULL)                      \
    X(INT,     enterTime,                enter_time,               164, NULL)                      \
    X(INT,     damageResidual,           damage_residual,          216, NULL)                      \
    X(INT,     inactivityTime,           inactivity_time,          220, NULL)                      \
    X(INT,     inactivityWarning,        inactivity_warning,       224, NULL)                      \
    X(INT,     lastUserinfoUpdate,       last_userinfo_update,     228, NULL)                      \
    X(INT,     userInfoFloodInfractions, user_info_flood_infractions, 232, NULL)                     \
    X(INT,     lastMapVoteTime,          last_map_vote_time,       236, NULL)                      \
    X(INT,     lastMapVoteIndex,         last_map_vote_index,      240, NULL)

/* clientSession_t. Reached as GameClient(n).sess. */
#define SESSION_FIELDS(X)                                                                          \
    X(INT,  sessionTeam,      session_team,      0, "One of the TEAM_* constants.")                 \
    X(INT,  spectatorTime,    spectator_time,    4, NULL)                                          \
    X(INT,  spectatorState,   spectator_state,   8, "One of the SPECTATOR_* constants.")           \
    X(INT,  spectatorClient,  spectator_client, 12, "Who a following spectator is watching.")      \
    X(INT,  weaponPrimary,    weapon_primary,   16, NULL)                                          \
    X(INT,  wins,             wins,             20, NULL)                                          \
    X(INT,  losses,           losses,           24, NULL)                                          \
    X(BOOL, teamLeader,       team_leader,      28, NULL)                                          \
    X(UINT, privileges,       privileges,       32, "One of the PRIV_* constants.")                \
    X(INT,  specOnly,         spec_only,        36, NULL)                                          \
    X(INT,  playQueue,        play_queue,       40, "Position in the play queue.")                 \
    X(BOOL, updatePlayQueue,  update_play_queue,44, NULL)                                          \
    X(INT,  muted,            muted,            48, "The read side of the mute command.")          \
    X(INT,  prevScore,        prev_score,       52, NULL)

/* raceInfo_t. Reached as GameClient(n).race. */
#define RACEINFO_FIELDS(X)                                                                         \
    X(BOOL,   racingActive,      racing_active,       0, NULL)                                     \
    X(INT,    startTime,         start_time,          4, NULL)                                     \
    X(INT,    lastTime,          last_time,           8, NULL)                                     \
    X(INTARR, best_race,         best_race,          12, "Per-checkpoint split times.")            \
    X(INTARR, current_race,      current_race,      268, NULL)                                     \
    X(INT,    currentCheckPoint, current_check_point, 524, NULL)                                     \
    X(BOOL,   weaponUsed,        weapon_used,       528, NULL)                                     \
    X(ENTREF, nextRacePoint,     next_race_point,   536, NULL)                                     \
    X(ENTREF, nextRacePoint2,    next_race_point2,  544, NULL)

/* expandedStatObj_t. Reached as GameClient(n).expanded_stats. */
#define EXPANDEDSTATS_FIELDS(X)                                                                    \
    X(UINT,    statId,                     stat_id,                        0, NULL)                \
    X(INT,     lastThinkTime,              last_think_time,                4, NULL)                \
    X(INT,     teamJoinTime,               team_join_time,                 8, NULL)                \
    X(INT,     totalPlayTime,              total_play_time,               12, NULL)                \
    X(INT,     serverRank,                 server_rank,                   16, NULL)                \
    X(BOOL,    serverRankIsTied,           server_rank_is_tied,           20, NULL)                \
    X(INT,     teamRank,                   team_rank,                     24, NULL)                \
    X(BOOL,    teamRankIsTied,             team_rank_is_tied,             28, NULL)                \
    X(INT,     numKills,                   num_kills,                     32, NULL)                \
    X(INT,     numDeaths,                  num_deaths,                    36, NULL)                \
    X(INT,     numSuicides,                num_suicides,                  40, NULL)                \
    X(INT,     numTeamKills,               num_team_kills,                44, NULL)                \
    X(INT,     numTeamKilled,              num_team_killed,               48, NULL)                \
    X(WEAPONS, numWeaponKills,             num_weapon_kills,              52, NULL)                \
    X(WEAPONS, numWeaponDeaths,            num_weapon_deaths,            116, NULL)                \
    X(WEAPONS, shotsFired,                 shots_fired,                  180, NULL)                \
    X(WEAPONS, shotsHit,                   shots_hit,                    244, NULL)                \
    X(WEAPONS, damageDealt,                damage_dealt,                 308, NULL)                \
    X(WEAPONS, damageTaken,                damage_taken,                 372, NULL)                \
    X(INTARR,  powerups,                   powerups,                     436, NULL)                \
    X(INTARR,  holdablePickups,            holdable_pickups,             500, NULL)                \
    X(WEAPONS, weaponPickups,              weapon_pickups,               528, NULL)                \
    X(WEAPONS, weaponUsageTime,            weapon_usage_time,            592, NULL)                \
    X(INT,     numCaptures,                num_captures,                 656, NULL)                \
    X(INT,     numAssists,                 num_assists,                  660, NULL)                \
    X(INT,     numDefends,                 num_defends,                  664, NULL)                \
    X(INT,     numHolyShits,               num_holy_shits,               668, NULL)                \
    X(INT,     totalDamageDealt,           total_damage_dealt,           672, NULL)                \
    X(INT,     totalDamageTaken,           total_damage_taken,           676, NULL)                \
    X(INT,     previousHealth,             previous_health,              680, NULL)                \
    X(INT,     previousArmor,              previous_armor,               684, NULL)                \
    X(INT,     numAmmoPickups,             num_ammo_pickups,             688, NULL)                \
    X(INT,     numFirstMegaHealthPickups,  num_first_mega_health_pickups,692, NULL)                \
    X(INT,     numMegaHealthPickups,       num_mega_health_pickups,      696, NULL)                \
    X(INT,     megaHealthPickupTime,       mega_health_pickup_time,      700, NULL)                \
    X(INT,     numHealthPickups,           num_health_pickups,           704, NULL)                \
    X(INT,     numFirstRedArmorPickups,    num_first_red_armor_pickups,  708, NULL)                \
    X(INT,     numRedArmorPickups,         num_red_armor_pickups,        712, NULL)                \
    X(INT,     redArmorPickupTime,         red_armor_pickup_time,        716, NULL)                \
    X(INT,     numFirstYellowArmorPickups, num_first_yellow_armor_pickups, 720, NULL)                \
    X(INT,     numYellowArmorPickups,      num_yellow_armor_pickups,     724, NULL)                \
    X(INT,     yellowArmorPickupTime,      yellow_armor_pickup_time,     728, NULL)                \
    X(INT,     numFirstGreenArmorPickups,  num_first_green_armor_pickups,732, NULL)                \
    X(INT,     numGreenArmorPickups,       num_green_armor_pickups,      736, NULL)                \
    X(INT,     greenArmorPickupTime,       green_armor_pickup_time,      740, NULL)                \
    X(INT,     numQuadDamagePickups,       num_quad_damage_pickups,      744, NULL)                \
    X(INT,     numQuadDamageKills,         num_quad_damage_kills,        748, NULL)                \
    X(INT,     numBattleSuitPickups,       num_battle_suit_pickups,      752, NULL)                \
    X(INT,     numRegenerationPickups,     num_regeneration_pickups,     756, NULL)                \
    X(INT,     numHastePickups,            num_haste_pickups,            760, NULL)                \
    X(INT,     numInvisibilityPickups,     num_invisibility_pickups,     764, NULL)                \
    X(INT,     numRedFlagPickups,          num_red_flag_pickups,         768, NULL)                \
    X(INT,     numBlueFlagPickups,         num_blue_flag_pickups,        772, NULL)                \
    X(INT,     numNeutralFlagPickups,      num_neutral_flag_pickups,     776, NULL)                \
    X(INT,     numMedkitPickups,           num_medkit_pickups,           780, NULL)                \
    X(INT,     numArmorPickups,            num_armor_pickups,            784, NULL)                \
    X(INT,     numDenials,                 num_denials,                  788, NULL)                \
    X(INT,     killStreak,                 kill_streak,                  792, NULL)                \
    X(INT,     maxKillStreak,              max_kill_streak,              796, NULL)                \
    X(INT,     xp,                         xp,                           800, NULL)                \
    X(INT,     domThreeFlagsTime,          dom_three_flags_time,         804, NULL)                \
    X(INT,     numMidairShotgunKills,      num_midair_shotgun_kills,     808, NULL)

/*
 * gclient_t. Reached as GameClient(n), or as Entity(n).client. ps, pers, sess, race and
 * expandedStats are sub-objects.
 */
#define GAMECLIENT_FIELDS(X)                                                                       \
    X(BOOL,   noclip,                noclip,                896, NULL)                             \
    X(INT,    lastCmdTime,           last_cmd_time,         900, NULL)                             \
    X(INT,    buttons,               buttons,               904, "Live button state; BUTTON_ATTACK and friends.") \
    X(INT,    oldbuttons,            oldbuttons,            908, NULL)                             \
    X(INT,    damage_armor,          damage_armor,          912, NULL)                             \
    X(INT,    damage_blood,          damage_blood,          916, NULL)                             \
    X(VEC3,   damage_from,           damage_from,           920, NULL)                             \
    X(BOOL,   damage_fromWorld,      damage_from_world,     932, NULL)                             \
    X(INT,    impressiveCount,       impressive_count,      936, NULL)                             \
    X(INT,    accuracyCount,         accuracy_count,        940, NULL)                             \
    X(INT,    accuracy_shots,        accuracy_shots,        944, "Whole-match shots, across every weapon.") \
    X(INT,    accuracy_hits,         accuracy_hits,         948, NULL)                             \
    X(INT,    lastClientKilled,      last_client_killed,    952, NULL)                             \
    X(INT,    lastKilledClient,      last_killed_client,    956, NULL)                             \
    X(INTARR, lastHurtClient,        last_hurt_client,      960, NULL)                             \
    X(INTARR, lastHurtMod,           last_hurt_mod,         968, NULL)                             \
    X(INTARR, lastHurtTime,          last_hurt_time,        976, NULL)                             \
    X(INT,    lastKillTime,          last_kill_time,        984, NULL)                             \
    X(INT,    lastGibTime,           last_gib_time,         988, NULL)                             \
    X(INT,    rampageCounter,        rampage_counter,       992, NULL)                             \
    X(INTARR, revengeCounter,        revenge_counter,       996, NULL)                             \
    X(INT,    respawnTime,           respawn_time,         1252, NULL)                             \
    X(INT,    rewardTime,            reward_time,          1256, NULL)                             \
    X(INT,    airOutTime,            air_out_time,         1260, NULL)                             \
    X(BOOL,   fireHeld,              fire_held,            1264, NULL)                             \
    X(ENTREF, hook,                  hook,                 1272, "The grapple entity, or None.")   \
    X(INT,    switchTeamTime,        switch_team_time,     1280, NULL)                             \
    X(INT,    timeResidual,          time_residual,        1284, NULL)                             \
    X(INT,    timeResidualScout,     time_residual_scout,  1288, NULL)                             \
    X(INT,    timeResidualArmor,     time_residual_armor,  1292, NULL)                             \
    X(INT,    timeResidualHealth,    time_residual_health, 1296, NULL)                             \
    X(INT,    timeResidualPingPOI,   time_residual_ping_poi,  1300, NULL)                             \
    X(INT,    timeResidualSpecInfo,  time_residual_spec_info, 1304, NULL)                             \
    X(BOOL,   healthRegenActive,     health_regen_active,  1308, NULL)                             \
    X(BOOL,   armorRegenActive,      armor_regen_active,   1312, NULL)                             \
    X(ENTREF, persistantPowerup,     persistant_powerup,   1320, NULL)                             \
    X(INT,    portalID,              portal_id,            1328, NULL)                             \
    X(INTARR, ammoTimes,             ammo_times,           1332, NULL)                             \
    X(INT,    invulnerabilityTime,   invulnerability_time, 1396, "The read side of set_invulnerability().") \
    X(INT,    ignoreChatsTime,       ignore_chats_time,    2212, NULL)                             \
    X(INT,    lastUserCmdTime,       last_user_cmd_time,   2216, NULL)                             \
    X(BOOL,   freezePlayer,          freeze_player,        2220, NULL)                             \
    X(INT,    deferredSpawnTime,     deferred_spawn_time,  2224, NULL)                             \
    X(INT,    deferredSpawnCount,    deferred_spawn_count, 2228, NULL)                             \
    X(INTARR, shotgunDmg,            shotgun_dmg,          2784, NULL)                             \
    X(INT,    round_shots,           round_shots,          3040, NULL)                             \
    X(INT,    round_hits,            round_hits,           3044, NULL)                             \
    X(INT,    round_damage,          round_damage,         3048, NULL)                             \
    X(BOOL,   queuedSpectatorFollow, queued_spectator_follow, 3052, NULL)                             \
    X(INT,    queuedSpectatorClient, queued_spectator_client, 3056, NULL)

/*
 * netchan_t. Reached as Client(n).netchan. The two 32 KiB fragment buffers are not exposed.
 */
#define NETCHAN_FIELDS(X)                                                                          \
    X(INT,  sock,                sock,                  0, NULL)                                   \
    X(INT,  dropped,             dropped,               4, "Packets lost between the last two received.") \
    X(INT,  qport,               qport,                28, NULL)                                   \
    X(INT,  incomingSequence,    incoming_sequence,    32, NULL)                                   \
    X(INT,  outgoingSequence,    outgoing_sequence,    36, NULL)                                   \
    X(INT,  fragmentSequence,    fragment_sequence,    40, NULL)                                   \
    X(INT,  fragmentLength,      fragment_length,      44, NULL)                                   \
    X(BOOL, unsentFragments,     unsent_fragments,  32816, NULL)                                   \
    X(INT,  unsentFragmentStart, unsent_fragment_start, 32820, NULL)                                   \
    X(INT,  unsentLength,        unsent_length,     32824, NULL)

/*
 * client_t. Reached as Client(n). The server's view of a connection: Client.ping is the
 * server's own measurement, where GameClient.ps.ping is the game module's copy.
 */
#define CLIENT_FIELDS(X)                                                                           \
    X(INT,     state,                   state,                     0, "One of the CS_* connection states.") \
    X(CHARBUF, userinfo,                userinfo,                  4, NULL)                        \
    X(INT,     reliableSequence,        reliable_sequence,     66564, "Commands queued. Minus reliable_acknowledge is the backlog; the ring holds 64.") \
    X(INT,     reliableAcknowledge,     reliable_acknowledge,  66568, NULL)                        \
    X(INT,     reliableSent,            reliable_sent,         66572, NULL)                        \
    X(INT,     messageAcknowledge,      message_acknowledge,   66576, NULL)                        \
    X(INT,     gamestateMessageNum,     gamestate_message_num, 66580, NULL)                        \
    X(INT,     challenge,               challenge,             66584, NULL)                        \
    X(INT,     lastUsercmd.serverTime,  last_usercmd_server_time,  66588, NULL)                        \
    X(INTARR,  lastUsercmd.angles,      last_usercmd_angles,   66592, NULL)                        \
    X(INT,     lastUsercmd.buttons,     last_usercmd_buttons,  66604, NULL)                        \
    X(BYTE,    lastUsercmd.weapon,      last_usercmd_weapon,   66608, NULL)                        \
    X(SCHAR,   lastUsercmd.forwardmove, last_usercmd_forwardmove,  66611, NULL)                        \
    X(SCHAR,   lastUsercmd.rightmove,   last_usercmd_rightmove,66612, NULL)                        \
    X(SCHAR,   lastUsercmd.upmove,      last_usercmd_upmove,   66613, NULL)                        \
    X(INT,     lastMessageNum,          last_message_num,      66616, NULL)                        \
    X(INT,     lastClientCommand,       last_client_command,   66620, NULL)                        \
    X(CHARBUF, lastClientCommandString, last_client_command_string, 66624, NULL)                       \
    X(CHARBUF, name,                    name,                  67656, "The server's copy of the name; pers.netname is the game module's.") \
    X(INT,     deltaMessage,            delta_message,         71860, NULL)                        \
    X(INT,     nextReliableTime,        next_reliable_time,    71864, NULL)                        \
    X(FLOAT,   floodCount,              flood_count,           71868, "The engine's token-bucket flood counter.") \
    X(INT,     lastPacketTime,          last_packet_time,      71872, "svs.time of the last packet; how idle detection is done.") \
    X(INT,     lastConnectTime,         last_connect_time,     71876, NULL)                        \
    X(INT,     nextSnapshotTime,        next_snapshot_time,    71880, NULL)                        \
    X(BOOL,    rateDelayed,             rate_delayed,          71884, NULL)                        \
    X(INT,     timeoutCount,            timeout_count,         71888, NULL)                        \
    X(INT,     ping,                    ping,                  92628, "The server's measurement. GameClient.ps.ping is the game module's copy.") \
    X(INT,     rate,                    rate,                  92632, NULL)                        \
    X(INT,     snapshotMsec,            snapshot_msec,         92636, NULL)                        \
    X(INT,     pureAuthentic,           pure_authentic,        92640, NULL)                        \
    X(BOOL,    gotCP,                   got_cp,                92644, NULL)                        \
    X(INT,     rageQuit,                rage_quit,            158304, NULL)                        \
    X(INT,     serverIdSequence,        server_id_sequence,   158308, NULL)                        \
    X(INT,     oldServerTime,           old_server_time,      158312, NULL)                        \
    X(U64,     steam_id,                steam_id,             158320, NULL)

/*
 * cvar_t. Reached as minqlxtended.cvar(name) or Cvar(name). string, value and integer are
 * hand-written in python_objects.c: they have to be written through Cvar_Set2.
 */
#define CVAR_FIELDS(X)                                                                             \
    X(CHARPTR, name,              name,               0, NULL)                                     \
    X(CHARPTR, resetString,       reset_string,      16, "What cvar_restart would put back.")      \
    X(CHARPTR, latchedString,     latched_string,    24, "Pending value for a CVAR_LATCH cvar.")   \
    X(CHARPTR, defaultString,     default_string,    32, NULL)                                     \
    X(CHARPTR, minimumString,     minimum_string,    40, NULL)                                     \
    X(CHARPTR, maximumString,     maximum_string,    48, NULL)                                     \
    X(INT,     flags,             flags,             56, "A CVAR_* bitfield.")                     \
    X(BOOL,    modified,          modified,          60, NULL)                                     \
    X(INT,     modificationCount, modification_count,68, NULL)

/*
 * gitem_t, as minqlxtended.Item(n) or items(). Read-only: bg_itemlist sits in .data.rel.ro,
 * which the loader mprotects PROT_READ after relocation, so a write faults on the game thread.
 */
#define ITEM_FIELDS(X)                                                                             \
    X(CHARPTR, classname,               classname,                  0, "The entity classname, as item_pickup reports it.") \
    X(CHARPTR, pickup_sound,            pickup_sound,               8, NULL)                       \
    X(CHARPTR, icon,                    icon,                      80, NULL)                       \
    X(CHARPTR, pickup_name,             pickup_name,               88, "The display name, e.g. \"Body Armor\".") \
    X(INT_RO,  quantity,                quantity,                  96, "How much it gives, or the respawn time for a weapon.") \
    X(INT_RO,  giType,                  gi_type,                  100, "One of the IT_* item types.")  \
    X(INT_RO,  giTag,                   gi_tag,                   104, "Meaning depends on gi_type; a WP_* for a weapon, a PW_* for a powerup.") \
    X(BOOL_RO, itemTimer,               item_timer,               108, NULL)                       \
    X(UINT_RO, maskGametypeRenderSkip,  mask_gametype_render_skip,112, NULL)                       \
    X(UINT_RO, maskGametypeForceSpawn,  mask_gametype_force_spawn,116, NULL)

/*
 * server_t, as the singleton minqlxtended.server. The server's own state for the loaded map,
 * which SV_SpawnServer wipes and rebuilds. For configstrings use configstring(index).
 */
#define SERVER_FIELDS(X)                                                                           \
    X(INT,  state,                state,                    0, "One of the SS_* server states. SS_GAME means a map is up and running.") \
    X(BOOL, restarting,           restarting,               4, "Set while a map_restart is in flight; configstring changes are sent during SS_LOADING when it is.") \
    X(INT,  serverId,             server_id,                8, "Changes on every map load. Clients carry it in every usercmd.") \
    X(INT,  restartedServerId,    restarted_server_id,     12, "What server_id was before a map_restart.")  \
    X(INT,  checksumFeed,         checksum_feed,           16, "The key the pure-server checksum strings are computed from.") \
    X(INT,  checksumFeedServerId, checksum_feed_server_id, 20, NULL)                               \
    X(INT,  snapshotCounter,      snapshot_counter,        24, NULL)                               \
    X(INT,  timeResidual,         time_residual,           28, "Milliseconds carried into the next frame; the engine runs a frame when this passes 1000/sv_fps.") \
    X(INT,  nextFrameTime,        next_frame_time,         32, NULL)                               \
    X(INT,  num_entities,         num_entities,        354364, "The server's own high-water mark, kept in step with level.num_entities.") \
    X(INT,  restartTime,          restart_time,        354380, NULL)

/*
 * serverStatic_t, as the singleton minqlxtended.server_static. svs.time keeps counting
 * across a map change, where level.time restarts. For clients use Player.connection.
 */
#define SERVERSTATIC_FIELDS(X)                                                                     \
    X(BOOL, initialized,           initialized,             0, "False until SV_Init has finished.") \
    X(INT,  time,                  time,                    4, "Strictly increasing across map changes, unlike level.time.") \
    X(INT,  snapFlagServerBit,     snap_flag_server_bit,    8, "Toggled by every SV_SpawnServer, so clients can tell snapshots of two maps apart.") \
    X(INT,  numSnapshotEntities,   num_snapshot_entities,  24, NULL)                               \
    X(INT,  nextSnapshotEntities,  next_snapshot_entities, 28, NULL)

// clang-format on

#endif /* ENGINE_FIELDS_H */
