"""Type stub for the `_minqlxtended` C extension.

GENERATED by tools/gen_stub.py. Don't edit it. Re-run that after changing the method
table, the struct sequence descriptors, the PyModule_AddIntMacro block in python_embed.c,
or the field lists in engine_fields.h.

The module is registered through PyImport_AppendInittab and only exists inside a running
qzeroded, so this file is the only description of it anything outside one can read.
"""

from typing import Any, Callable, Final, Iterator, Sequence, SupportsIndex, overload

__version__: str
DEBUG: bool


# --- struct sequences ---------------------------------------------------------

# Snapshots, taken when you ask for them. Tuple subclasses: index them, unpack
# them, or read the fields by name. _replace() gives a copy with fields changed.

class PlayerInfo(tuple[Any, ...]):
    _fields: Final[tuple[str, ...]]
    n_fields: Final[int]
    n_sequence_fields: Final[int]
    n_unnamed_fields: Final[int]
    def __init__(self, sequence: Any, /) -> None: ...
    @property
    def client_id(self) -> Any: ...
    @property
    def name(self) -> Any: ...
    @property
    def connection_state(self) -> Any: ...
    @property
    def userinfo(self) -> Any: ...
    @property
    def steam_id(self) -> Any: ...
    @property
    def team(self) -> Any: ...
    @property
    def privileges(self) -> Any: ...
    def _replace(self, **fields: Any) -> "PlayerInfo": ...

class PlayerState(tuple[Any, ...]):
    _fields: Final[tuple[str, ...]]
    n_fields: Final[int]
    n_sequence_fields: Final[int]
    n_unnamed_fields: Final[int]
    def __init__(self, sequence: Any, /) -> None: ...
    @property
    def is_alive(self) -> Any: ...
    @property
    def position(self) -> Any: ...
    @property
    def velocity(self) -> Any: ...
    @property
    def health(self) -> Any: ...
    @property
    def armor(self) -> Any: ...
    @property
    def speed(self) -> Any: ...
    @property
    def gravity(self) -> Any: ...
    @property
    def noclip(self) -> Any: ...
    @property
    def weapon(self) -> Any: ...
    @property
    def weapons(self) -> Any: ...
    @property
    def ammo(self) -> Any: ...
    @property
    def powerups(self) -> Any: ...
    @property
    def holdable(self) -> Any: ...
    @property
    def flight(self) -> Any: ...
    @property
    def is_frozen(self) -> Any: ...
    @property
    def keys(self) -> Any: ...
    @property
    def flags(self) -> Any: ...
    @property
    def god(self) -> Any: ...
    @property
    def notarget(self) -> Any: ...
    def _replace(self, **fields: Any) -> "PlayerState": ...

class PlayerStats(tuple[Any, ...]):
    _fields: Final[tuple[str, ...]]
    n_fields: Final[int]
    n_sequence_fields: Final[int]
    n_unnamed_fields: Final[int]
    def __init__(self, sequence: Any, /) -> None: ...
    @property
    def score(self) -> Any: ...
    @property
    def kills(self) -> Any: ...
    @property
    def deaths(self) -> Any: ...
    @property
    def damage_dealt(self) -> Any: ...
    @property
    def damage_taken(self) -> Any: ...
    @property
    def time(self) -> Any: ...
    @property
    def ping(self) -> Any: ...
    def _replace(self, **fields: Any) -> "PlayerStats": ...

class Vector3(tuple[Any, ...]):
    _fields: Final[tuple[str, ...]]
    n_fields: Final[int]
    n_sequence_fields: Final[int]
    n_unnamed_fields: Final[int]
    def __init__(self, sequence: Any, /) -> None: ...
    @property
    def x(self) -> Any: ...
    @property
    def y(self) -> Any: ...
    @property
    def z(self) -> Any: ...
    def _replace(self, **fields: Any) -> "Vector3": ...

class Weapons(tuple[Any, ...]):
    _fields: Final[tuple[str, ...]]
    n_fields: Final[int]
    n_sequence_fields: Final[int]
    n_unnamed_fields: Final[int]
    def __init__(self, sequence: Any, /) -> None: ...
    @property
    def g(self) -> Any: ...
    @property
    def mg(self) -> Any: ...
    @property
    def sg(self) -> Any: ...
    @property
    def gl(self) -> Any: ...
    @property
    def rl(self) -> Any: ...
    @property
    def lg(self) -> Any: ...
    @property
    def rg(self) -> Any: ...
    @property
    def pg(self) -> Any: ...
    @property
    def bfg(self) -> Any: ...
    @property
    def gh(self) -> Any: ...
    @property
    def ng(self) -> Any: ...
    @property
    def pl(self) -> Any: ...
    @property
    def cg(self) -> Any: ...
    @property
    def hmg(self) -> Any: ...
    @property
    def hands(self) -> Any: ...
    def _replace(self, **fields: Any) -> "Weapons": ...

class Powerups(tuple[Any, ...]):
    _fields: Final[tuple[str, ...]]
    n_fields: Final[int]
    n_sequence_fields: Final[int]
    n_unnamed_fields: Final[int]
    def __init__(self, sequence: Any, /) -> None: ...
    @property
    def quad(self) -> Any: ...
    @property
    def battlesuit(self) -> Any: ...
    @property
    def haste(self) -> Any: ...
    @property
    def invisibility(self) -> Any: ...
    @property
    def regeneration(self) -> Any: ...
    @property
    def invulnerability(self) -> Any: ...
    def _replace(self, **fields: Any) -> "Powerups": ...

class Flight(tuple[Any, ...]):
    _fields: Final[tuple[str, ...]]
    n_fields: Final[int]
    n_sequence_fields: Final[int]
    n_unnamed_fields: Final[int]
    def __init__(self, sequence: Any, /) -> None: ...
    @property
    def fuel(self) -> Any: ...
    @property
    def max_fuel(self) -> Any: ...
    @property
    def thrust(self) -> Any: ...
    @property
    def refuel(self) -> Any: ...
    def _replace(self, **fields: Any) -> "Flight": ...

class Keys(tuple[Any, ...]):
    _fields: Final[tuple[str, ...]]
    n_fields: Final[int]
    n_sequence_fields: Final[int]
    n_unnamed_fields: Final[int]
    def __init__(self, sequence: Any, /) -> None: ...
    @property
    def silver(self) -> Any: ...
    @property
    def gold(self) -> Any: ...
    @property
    def master(self) -> Any: ...
    def _replace(self, **fields: Any) -> "Keys": ...

class DemoStatus(tuple[Any, ...]):
    _fields: Final[tuple[str, ...]]
    n_fields: Final[int]
    n_sequence_fields: Final[int]
    n_unnamed_fields: Final[int]
    def __init__(self, sequence: Any, /) -> None: ...
    @property
    def recording(self) -> Any: ...
    @property
    def requested(self) -> Any: ...
    @property
    def path(self) -> Any: ...
    def _replace(self, **fields: Any) -> "DemoStatus": ...

class ReliableStatus(tuple[Any, ...]):
    _fields: Final[tuple[str, ...]]
    n_fields: Final[int]
    n_sequence_fields: Final[int]
    n_unnamed_fields: Final[int]
    def __init__(self, sequence: Any, /) -> None: ...
    @property
    def enabled(self) -> Any: ...
    @property
    def watermark(self) -> Any: ...
    @property
    def burst(self) -> Any: ...
    @property
    def waiting(self) -> Any: ...
    @property
    def queued(self) -> Any: ...
    @property
    def merged(self) -> Any: ...
    @property
    def bypassed(self) -> Any: ...
    @property
    def backlog(self) -> Any: ...
    @property
    def worst_backlog(self) -> Any: ...
    @property
    def worst_slot(self) -> Any: ...
    def _replace(self, **fields: Any) -> "ReliableStatus": ...

class StatPowerups(tuple[Any, ...]):
    _fields: Final[tuple[str, ...]]
    n_fields: Final[int]
    n_sequence_fields: Final[int]
    n_unnamed_fields: Final[int]
    def __init__(self, sequence: Any, /) -> None: ...
    @property
    def spawnarmor(self) -> Any: ...
    @property
    def redflag(self) -> Any: ...
    @property
    def blueflag(self) -> Any: ...
    @property
    def neutralflag(self) -> Any: ...
    @property
    def quad(self) -> Any: ...
    @property
    def battlesuit(self) -> Any: ...
    @property
    def haste(self) -> Any: ...
    @property
    def invisibility(self) -> Any: ...
    @property
    def regeneration(self) -> Any: ...
    @property
    def flight(self) -> Any: ...
    @property
    def invulnerability(self) -> Any: ...
    @property
    def scout(self) -> Any: ...
    @property
    def guard(self) -> Any: ...
    @property
    def doubler(self) -> Any: ...
    @property
    def armorregen(self) -> Any: ...
    @property
    def freeze(self) -> Any: ...
    def _replace(self, **fields: Any) -> "StatPowerups": ...

class StatHoldables(tuple[Any, ...]):
    _fields: Final[tuple[str, ...]]
    n_fields: Final[int]
    n_sequence_fields: Final[int]
    n_unnamed_fields: Final[int]
    def __init__(self, sequence: Any, /) -> None: ...
    @property
    def teleporter(self) -> Any: ...
    @property
    def medkit(self) -> Any: ...
    @property
    def kamikaze(self) -> Any: ...
    @property
    def portal(self) -> Any: ...
    @property
    def invulnerability(self) -> Any: ...
    @property
    def flight(self) -> Any: ...
    def _replace(self, **fields: Any) -> "StatHoldables": ...

class PlayerExpandedStats(tuple[Any, ...]):
    _fields: Final[tuple[str, ...]]
    n_fields: Final[int]
    n_sequence_fields: Final[int]
    n_unnamed_fields: Final[int]
    def __init__(self, sequence: Any, /) -> None: ...
    @property
    def play_time(self) -> Any: ...
    @property
    def server_rank(self) -> Any: ...
    @property
    def server_rank_tied(self) -> Any: ...
    @property
    def team_rank(self) -> Any: ...
    @property
    def team_rank_tied(self) -> Any: ...
    @property
    def kills(self) -> Any: ...
    @property
    def deaths(self) -> Any: ...
    @property
    def suicides(self) -> Any: ...
    @property
    def team_kills(self) -> Any: ...
    @property
    def team_killed(self) -> Any: ...
    @property
    def damage_dealt(self) -> Any: ...
    @property
    def damage_taken(self) -> Any: ...
    @property
    def captures(self) -> Any: ...
    @property
    def assists(self) -> Any: ...
    @property
    def defends(self) -> Any: ...
    @property
    def holy_shits(self) -> Any: ...
    @property
    def denials(self) -> Any: ...
    @property
    def kill_streak(self) -> Any: ...
    @property
    def max_kill_streak(self) -> Any: ...
    @property
    def midair_shotgun_kills(self) -> Any: ...
    @property
    def quad_damage_kills(self) -> Any: ...
    @property
    def xp(self) -> Any: ...
    @property
    def dom_three_flags_time(self) -> Any: ...
    @property
    def weapon_kills(self) -> Any: ...
    @property
    def weapon_deaths(self) -> Any: ...
    @property
    def shots_fired(self) -> Any: ...
    @property
    def shots_hit(self) -> Any: ...
    @property
    def weapon_damage_dealt(self) -> Any: ...
    @property
    def weapon_damage_taken(self) -> Any: ...
    @property
    def weapon_pickups(self) -> Any: ...
    @property
    def weapon_time(self) -> Any: ...
    @property
    def ammo_pickups(self) -> Any: ...
    @property
    def health_pickups(self) -> Any: ...
    @property
    def mega_health_pickups(self) -> Any: ...
    @property
    def first_mega_health_pickups(self) -> Any: ...
    @property
    def mega_health_pickup_time(self) -> Any: ...
    @property
    def armor_pickups(self) -> Any: ...
    @property
    def red_armor_pickups(self) -> Any: ...
    @property
    def first_red_armor_pickups(self) -> Any: ...
    @property
    def red_armor_pickup_time(self) -> Any: ...
    @property
    def yellow_armor_pickups(self) -> Any: ...
    @property
    def first_yellow_armor_pickups(self) -> Any: ...
    @property
    def yellow_armor_pickup_time(self) -> Any: ...
    @property
    def green_armor_pickups(self) -> Any: ...
    @property
    def first_green_armor_pickups(self) -> Any: ...
    @property
    def green_armor_pickup_time(self) -> Any: ...
    @property
    def quad_damage_pickups(self) -> Any: ...
    @property
    def battle_suit_pickups(self) -> Any: ...
    @property
    def regeneration_pickups(self) -> Any: ...
    @property
    def haste_pickups(self) -> Any: ...
    @property
    def invisibility_pickups(self) -> Any: ...
    @property
    def medkit_pickups(self) -> Any: ...
    @property
    def red_flag_pickups(self) -> Any: ...
    @property
    def blue_flag_pickups(self) -> Any: ...
    @property
    def neutral_flag_pickups(self) -> Any: ...
    @property
    def powerup_pickups(self) -> Any: ...
    @property
    def holdable_pickups(self) -> Any: ...
    def _replace(self, **fields: Any) -> "PlayerExpandedStats": ...


# --- live engine views --------------------------------------------------------

# Not snapshots: reading an attribute dereferences the engine there and then, and
# assigning writes straight through. Game thread only. An attribute written as a
# property is read-only; the engine offers no way to set it.

class IntArray:
    def __len__(self) -> int: ...
    @overload
    def __getitem__(self, index: SupportsIndex, /) -> int: ...
    @overload
    def __getitem__(self, index: slice, /) -> list[int]: ...
    def __setitem__(self, index: int, value: int) -> None: ...
    def __iter__(self) -> Iterator[int]: ...

class CvarIterator:
    def __iter__(self) -> "CvarIterator": ...
    def __next__(self) -> Cvar: ...

class EntityIterator:
    def __iter__(self) -> "EntityIterator": ...
    def __next__(self) -> Entity: ...

class ItemIterator:
    def __iter__(self) -> "ItemIterator": ...
    def __next__(self) -> Item: ...

class Level:
    gentity_size: int
    num_entities: int
    warmup_time: int
    maxclients: int
    time: int
    frametime: int
    start_time: int
    team_scores: IntArray
    next_team_info_time: int
    new_session: bool
    restarted: bool
    shuffle_pending: bool
    shuffle_ready_time: int
    num_connected_clients: int
    num_non_spectator_clients: int
    num_playing_clients: int
    num_ready_clients: int
    num_ready_humans: int
    num_standard_clients: int
    sorted_clients: IntArray
    follow1: int
    follow2: int
    snd_fry: int
    warmup_modification_count: int
    vote_string: str
    vote_display_string: str
    vote_execute_time: int
    vote_time: int
    vote_yes: int
    vote_no: int
    pending_vote_caller: int
    spawning: bool
    num_spawn_vars: int
    num_spawn_var_chars: int
    intermission_queued: int
    intermission_time: int
    ready_to_exit: bool
    voting_ended: bool
    exit_time: int
    intermission_origin: Vector3
    intermission_angle: Vector3
    location_linked: bool
    location_head: Entity | None
    time_pause_begin: int
    time_overtime: int
    time_initial_key_spawn: int
    time_initial_powerup_spawn: int
    body_que_index: int
    @property
    def body_que(self) -> tuple[Entity | None, ...]: ...
    portal_sequence: int
    game_stats_reported: bool
    map_is_training_map: bool
    client_num_1st_player: int
    client_num_2nd_player: int
    scoreboard_archive1: str
    scoreboard_archive2: str
    first_scorer: str
    last_scorer: str
    last_team_scorer: str
    first_frag: str
    red_flag_origin: Vector3
    blue_flag_origin: Vector3
    spawn_count: IntArray
    rune_spawns: IntArray
    item_count: IntArray
    sudden_death_respawn_delay: int
    sudden_death_respawn_delay_last_announced: int
    num_red_armor_pickups: IntArray
    num_yellow_armor_pickups: IntArray
    num_green_armor_pickups: IntArray
    num_mega_health_pickups: IntArray
    num_quad_damage_pickups: IntArray
    num_battle_suit_pickups: IntArray
    num_regeneration_pickups: IntArray
    num_haste_pickups: IntArray
    num_invisibility_pickups: IntArray
    quad_damage_possession_time: IntArray
    battle_suit_possession_time: IntArray
    regeneration_possession_time: IntArray
    haste_possession_time: IntArray
    invisibility_possession_time: IntArray
    num_flag_pickups: IntArray
    num_medkit_pickups: IntArray
    flag_possession_time: IntArray
    @property
    def domination_points(self) -> tuple[Entity | None, ...]: ...
    domination_point_count: int
    domination_points_tallied: int
    race_point_count: int
    disable_drop_weapon: bool
    team_shuffle_active: bool
    last_team_scores: IntArray
    last_team_round_scores: IntArray
    attacking_team: int
    last_team_count_sent: int
    infected_conscript: int
    last_zombie_survivor: int
    zombie_score_time: int
    last_infection_time: int
    intermission_map_votes: IntArray
    match_forfeited: bool
    all_ready_time: int
    notify_cvar_change: bool
    notify_cvar_change_time: int
    last_lead_change_time: int
    last_lead_change_client: int
    last_lead_change_elapsed_time: int
    num_playing: int
    pause_begin: int
    @property
    def round(self) -> RoundStateView: ...
    round_state: int
    vote_caller: int

class MatchState:
    auto_action_state: int
    pause_caller: int
    paused_by_server: bool
    team_locked: IntArray
    timeouts_used: IntArray
    unpause_time: int

class RoundStateView:
    current: int
    next: int
    time_next: int
    start_time: int
    turn: int
    round: int
    prev_round_winning_team: int
    touch: bool
    capture: bool

class EntityState:
    number: int
    e_type: int
    e_flags: int
    pos_type: int
    pos_time: int
    pos_duration: int
    pos_base: Vector3
    pos_delta: Vector3
    pos_gravity: float
    apos_type: int
    apos_time: int
    apos_duration: int
    apos_base: Vector3
    apos_delta: Vector3
    apos_gravity: float
    time: int
    time2: int
    origin: Vector3
    origin2: Vector3
    angles: Vector3
    angles2: Vector3
    other_entity_num: int
    other_entity_num2: int
    ground_entity_num: int
    constant_light: int
    loop_sound: int
    modelindex: int
    modelindex2: int
    client_num: int
    frame: int
    solid: int
    event: int
    event_parm: int
    powerups: int
    health: int
    armor: int
    weapon: int
    location: int
    legs_anim: int
    torso_anim: int
    generic1: int
    jump_time: int
    double_jumped: int

class EntityShared:
    linked: bool
    linkcount: int
    sv_flags: int
    single_client: int
    bmodel: bool
    mins: Vector3
    maxs: Vector3
    contents: int
    absmin: Vector3
    absmax: Vector3
    current_origin: Vector3
    current_angles: Vector3
    owner_num: int

class Entity:
    def __init__(self, number: int) -> None: ...
    inuse: bool
    @property
    def classname(self) -> str | None: ...
    spawnflags: int
    never_free: bool
    flags: int
    @property
    def model(self) -> str | None: ...
    @property
    def model2(self) -> str | None: ...
    freetime: int
    event_time: int
    free_after_event: bool
    unlink_after_event: bool
    physics_object: bool
    physics_bounce: float
    clipmask: int
    mover_state: int
    sound_pos1: int
    sound1to2: int
    sound2to1: int
    sound_pos2: int
    sound_loop: int
    parent: Entity | None
    next_train: Entity | None
    prev_train: Entity | None
    pos1: Vector3
    pos2: Vector3
    @property
    def message(self) -> str | None: ...
    @property
    def cvar(self) -> str | None: ...
    @property
    def tour_point_target(self) -> str | None: ...
    @property
    def tour_point_target_name(self) -> str | None: ...
    @property
    def noise(self) -> str | None: ...
    timestamp: int
    angle: float
    @property
    def target(self) -> str | None: ...
    @property
    def targetname(self) -> str | None: ...
    @property
    def target_shader_name(self) -> str | None: ...
    @property
    def target_shader_new_name(self) -> str | None: ...
    target_ent: Entity | None
    speed: float
    movedir: Vector3
    nextthink: int
    think: int | None
    framethink: int | None
    reached: int | None
    blocked: int | None
    touch: int | None
    use: int | None
    pain: int | None
    die: int | None
    pain_debounce_time: int
    fly_sound_debounce_time: int
    health: int
    takedamage: bool
    damage: int
    damage_factor: int
    splash_damage: int
    splash_radius: int
    method_of_death: int
    splash_method_of_death: int
    count: int
    enemy: Entity | None
    activator: Entity | None
    @property
    def team(self) -> str | None: ...
    teammaster: Entity | None
    teamchain: Entity | None
    kamikaze_time: int
    kamikaze_shock_time: int
    watertype: int
    waterlevel: int
    noise_index: int
    bouncecount: int
    wait: float
    random: float
    spawn_time: int
    pickup_count: int
    @property
    def client(self) -> GameClient | None: ...
    @property
    def number(self) -> int: ...
    @property
    def r(self) -> EntityShared: ...
    @property
    def s(self) -> EntityState: ...

class PlayerStateView:
    command_time: int
    pm_type: int
    bob_cycle: int
    pm_flags: int
    pm_time: int
    origin: Vector3
    velocity: Vector3
    weapon_time: int
    gravity: int
    speed: int
    delta_angles: IntArray
    ground_entity_num: int
    legs_timer: int
    legs_anim: int
    torso_timer: int
    torso_anim: int
    movement_dir: int
    grapple_point: Vector3
    e_flags: int
    event_sequence: int
    events: IntArray
    event_parms: IntArray
    external_event: int
    external_event_parm: int
    client_num: int
    location: int
    weapon: int
    weapon_primary: int
    weaponstate: int
    fov: int
    viewangles: Vector3
    viewheight: int
    damage_event: int
    damage_yaw: int
    damage_pitch: int
    damage_count: int
    stats: IntArray
    persistant: IntArray
    powerups: IntArray
    ammo: IntArray
    generic1: int
    loop_sound: int
    jumppad_ent: int
    jump_time: int
    double_jumped: int
    crouch_time: int
    crouch_slide_time: int
    forwardmove: int
    rightmove: int
    upmove: int
    ping: int
    pmove_framecount: int
    jumppad_frame: int
    entity_event_sequence: int
    freezetime: int
    thawtime: int
    thaw_client_num_valid: int
    thaw_client_num: int
    respawn_time: int
    local_persistant: IntArray
    round_damage: int
    round_shots: int
    round_hits: int

class TeamState:
    state: int
    captures: int
    basedefense: int
    carrierdefense: int
    flagrecovery: int
    fragcarrier: int
    assists: int
    flagruntime: int
    flagrunrelays: int
    lasthurtcarrier: int
    lastreturnedflag: int
    lastfraggedcarrier: int

class Persistant:
    connected: int
    cmd_server_time: int
    cmd_angles: IntArray
    cmd_buttons: int
    cmd_weapon: int
    cmd_weapon_primary: int
    cmd_fov: int
    cmd_forwardmove: int
    cmd_rightmove: int
    cmd_upmove: int
    cmd_double_tap: int
    local_client: bool
    initial_spawn: bool
    predict_item_pickup: bool
    netname: str
    country: str
    steam_id: int
    max_health: int
    vote_count: int
    vote_state: int
    complaints: int
    complaint_client: int
    complaint_end_time: int
    damage_from_teammates: int
    damage_to_teammates: int
    ready: bool
    autoaction: int
    timeouts: int
    enter_time: int
    damage_residual: int
    inactivity_time: int
    inactivity_warning: int
    last_userinfo_update: int
    user_info_flood_infractions: int
    last_map_vote_time: int
    last_map_vote_index: int
    @property
    def team_state(self) -> TeamState: ...

class Session:
    session_team: int
    spectator_time: int
    spectator_state: int
    spectator_client: int
    weapon_primary: int
    wins: int
    losses: int
    team_leader: bool
    privileges: int
    spec_only: int
    play_queue: int
    update_play_queue: bool
    muted: int
    prev_score: int

class RaceInfo:
    racing_active: bool
    start_time: int
    last_time: int
    best_race: IntArray
    current_race: IntArray
    current_check_point: int
    weapon_used: bool
    next_race_point: Entity | None
    next_race_point2: Entity | None

class ExpandedStats:
    stat_id: int
    last_think_time: int
    team_join_time: int
    total_play_time: int
    server_rank: int
    server_rank_is_tied: bool
    team_rank: int
    team_rank_is_tied: bool
    num_kills: int
    num_deaths: int
    num_suicides: int
    num_team_kills: int
    num_team_killed: int
    @property
    def num_weapon_kills(self) -> Weapons: ...
    @property
    def num_weapon_deaths(self) -> Weapons: ...
    @property
    def shots_fired(self) -> Weapons: ...
    @property
    def shots_hit(self) -> Weapons: ...
    @property
    def damage_dealt(self) -> Weapons: ...
    @property
    def damage_taken(self) -> Weapons: ...
    powerups: IntArray
    holdable_pickups: IntArray
    @property
    def weapon_pickups(self) -> Weapons: ...
    @property
    def weapon_usage_time(self) -> Weapons: ...
    num_captures: int
    num_assists: int
    num_defends: int
    num_holy_shits: int
    total_damage_dealt: int
    total_damage_taken: int
    previous_health: int
    previous_armor: int
    num_ammo_pickups: int
    num_first_mega_health_pickups: int
    num_mega_health_pickups: int
    mega_health_pickup_time: int
    num_health_pickups: int
    num_first_red_armor_pickups: int
    num_red_armor_pickups: int
    red_armor_pickup_time: int
    num_first_yellow_armor_pickups: int
    num_yellow_armor_pickups: int
    yellow_armor_pickup_time: int
    num_first_green_armor_pickups: int
    num_green_armor_pickups: int
    green_armor_pickup_time: int
    num_quad_damage_pickups: int
    num_quad_damage_kills: int
    num_battle_suit_pickups: int
    num_regeneration_pickups: int
    num_haste_pickups: int
    num_invisibility_pickups: int
    num_red_flag_pickups: int
    num_blue_flag_pickups: int
    num_neutral_flag_pickups: int
    num_medkit_pickups: int
    num_armor_pickups: int
    num_denials: int
    kill_streak: int
    max_kill_streak: int
    xp: int
    dom_three_flags_time: int
    num_midair_shotgun_kills: int

class GameClient:
    def __init__(self, client_id: int) -> None: ...
    noclip: bool
    last_cmd_time: int
    buttons: int
    oldbuttons: int
    damage_armor: int
    damage_blood: int
    damage_from: Vector3
    damage_from_world: bool
    impressive_count: int
    accuracy_count: int
    accuracy_shots: int
    accuracy_hits: int
    last_client_killed: int
    last_killed_client: int
    last_hurt_client: IntArray
    last_hurt_mod: IntArray
    last_hurt_time: IntArray
    last_kill_time: int
    last_gib_time: int
    rampage_counter: int
    revenge_counter: IntArray
    respawn_time: int
    reward_time: int
    air_out_time: int
    fire_held: bool
    hook: Entity | None
    switch_team_time: int
    time_residual: int
    time_residual_scout: int
    time_residual_armor: int
    time_residual_health: int
    time_residual_ping_poi: int
    time_residual_spec_info: int
    health_regen_active: bool
    armor_regen_active: bool
    persistant_powerup: Entity | None
    portal_id: int
    ammo_times: IntArray
    invulnerability_time: int
    ignore_chats_time: int
    last_user_cmd_time: int
    freeze_player: bool
    deferred_spawn_time: int
    deferred_spawn_count: int
    shotgun_dmg: IntArray
    round_shots: int
    round_hits: int
    round_damage: int
    queued_spectator_follow: bool
    queued_spectator_client: int
    @property
    def expanded_stats(self) -> ExpandedStats: ...
    @property
    def id(self) -> int: ...
    @property
    def pers(self) -> Persistant: ...
    @property
    def ps(self) -> PlayerStateView: ...
    @property
    def race(self) -> RaceInfo: ...
    @property
    def sess(self) -> Session: ...

class Netchan:
    sock: int
    dropped: int
    qport: int
    incoming_sequence: int
    outgoing_sequence: int
    fragment_sequence: int
    fragment_length: int
    unsent_fragments: bool
    unsent_fragment_start: int
    unsent_length: int

class Client:
    def __init__(self, client_id: int) -> None: ...
    state: int
    userinfo: str
    reliable_sequence: int
    reliable_acknowledge: int
    reliable_sent: int
    message_acknowledge: int
    gamestate_message_num: int
    challenge: int
    last_usercmd_server_time: int
    last_usercmd_angles: IntArray
    last_usercmd_buttons: int
    last_usercmd_weapon: int
    last_usercmd_forwardmove: int
    last_usercmd_rightmove: int
    last_usercmd_upmove: int
    last_message_num: int
    last_client_command: int
    last_client_command_string: str
    name: str
    delta_message: int
    next_reliable_time: int
    flood_count: float
    last_packet_time: int
    last_connect_time: int
    next_snapshot_time: int
    rate_delayed: bool
    timeout_count: int
    ping: int
    rate: int
    snapshot_msec: int
    pure_authentic: int
    got_cp: bool
    rage_quit: int
    server_id_sequence: int
    old_server_time: int
    steam_id: int
    @property
    def address(self) -> str: ...
    @property
    def address_type(self) -> int: ...
    @property
    def id(self) -> int: ...
    @property
    def ip(self) -> str: ...
    @property
    def netchan(self) -> Netchan: ...
    @property
    def port(self) -> int: ...

class Cvar:
    def __init__(self, name: str) -> None: ...
    @property
    def name(self) -> str | None: ...
    @property
    def reset_string(self) -> str | None: ...
    @property
    def latched_string(self) -> str | None: ...
    @property
    def default_string(self) -> str | None: ...
    @property
    def minimum_string(self) -> str | None: ...
    @property
    def maximum_string(self) -> str | None: ...
    flags: int
    modified: bool
    modification_count: int
    integer: int
    string: str
    value: float
    def set(self, value: str, force: bool = ...) -> None: ...

class Item:
    def __init__(self, number: int) -> None: ...
    @property
    def classname(self) -> str | None: ...
    @property
    def pickup_sound(self) -> str | None: ...
    @property
    def icon(self) -> str | None: ...
    @property
    def pickup_name(self) -> str | None: ...
    @property
    def quantity(self) -> int: ...
    @property
    def gi_type(self) -> int: ...
    @property
    def gi_tag(self) -> int: ...
    @property
    def item_timer(self) -> bool: ...
    @property
    def mask_gametype_render_skip(self) -> int: ...
    @property
    def mask_gametype_force_spawn(self) -> int: ...
    @property
    def number(self) -> int: ...

class Server:
    state: int
    restarting: bool
    server_id: int
    restarted_server_id: int
    checksum_feed: int
    checksum_feed_server_id: int
    snapshot_counter: int
    time_residual: int
    next_frame_time: int
    num_entities: int
    restart_time: int

class ServerStatic:
    initialized: bool
    time: int
    snap_flag_server_bit: int
    num_snapshot_entities: int
    next_snapshot_entities: int


# --- singletons ---------------------------------------------------------------

level: Level
match_state: MatchState
server: Server
server_static: ServerStatic


# --- exceptions ---------------------------------------------------------------

class EngineStateError(RuntimeError):
    """The engine is not in a state where that question has an answer."""


# --- functions ----------------------------------------------------------------

def add_console_command(name: str, /) -> None: ...
def add_event(entity_id: int, event: int, event_parm: int = ..., /) -> None: ...
def callvote(vote: str, display: str, time: int = ..., caller_id: int = ..., /) -> None: ...
def client_command(client_id: int, cmd: str, /) -> bool: ...
def console_command(cmd: str, /) -> None: ...
def console_print(text: str, /) -> None: ...
def cvar(name: str, /) -> Cvar | None: ...
def cvars() -> Iterator[Cvar]: ...
def demo_status(client_id: int, /) -> DemoStatus: ...
def destroy_kamikaze_timers() -> bool: ...
def dev_print_items() -> None: ...
def drop_holdable(client_id: int, /) -> bool: ...
def drop_item(client_id: int, item_id: int, angle: float = ..., /) -> int | None: ...
def entities(inuse: bool = ..., etype: int | None = ..., start: int = ...,
             stop: int = ..., classname: str | None = ...) -> Iterator[Entity]: ...
def force_vote(pass_it: bool, /) -> bool: ...
def force_weapon_respawn_time(respawn_time: int, /) -> bool: ...
def get_configstring(index: int, /) -> str: ...
def get_cvar(name: str, /) -> str | None: ...
def get_userinfo(client_id: int, /) -> str | None: ...
def items() -> Iterator[Item]: ...
def kick(client_id: int, reason: str | None, /) -> None: ...
def link_entity(entity_id: int, /) -> bool: ...
def player_expanded_stats(client_id: int, /) -> PlayerExpandedStats | None: ...
def player_info(client_id: int, /) -> PlayerInfo | None: ...
def player_spawn(client_id: int, /) -> bool: ...
def player_state(client_id: int, /) -> PlayerState | None: ...
def player_stats(client_id: int, /) -> PlayerStats | None: ...
def players_info() -> list[PlayerInfo | None]: ...
def register_handler(event: str, handler: Callable[..., Any] | None, /) -> None: ...
def reliable_status() -> ReliableStatus: ...
def remove_dropped_items() -> bool: ...
def remove_entity(entity_id: int, /) -> bool: ...
def replace_items(entity: int | str, item: int | str, /) -> bool: ...
def reset_player_weapon_stats(client_id: int, /) -> bool: ...
def send_server_command(client_id: int | None, cmd: str, /) -> bool: ...
def set_configstring(index: int, value: str, /) -> None: ...
def set_cvar(name: str, value: str, flags: int = ..., force: bool = ...) -> Cvar: ...
def set_cvar_limit(name: str, value: str, minimum: str, maximum: str, flags: int = ..., /) -> None: ...
def slay_with_mod(client_id: int, mod: int, /) -> bool: ...
def spawn_entity(classname: str, keys: dict[str, str | int | float | Sequence[float]] | None = ..., /) -> Entity | None: ...
def spawn_item(item_id: int, x: int, y: int, z: int, /) -> bool: ...
def start_demo(client_id: int, /) -> bool: ...
def stop_demo(client_id: int, /) -> bool: ...
def unlink_entity(entity_id: int, /) -> bool: ...


# --- constants ----------------------------------------------------------------

# All int. The package rebinds most of these to enum members in _enums.py;
# what the C module itself exports is a plain int.

RET_NONE: int
RET_STOP: int
RET_STOP_EVENT: int
RET_STOP_ALL: int
RET_USAGE: int
PRI_HIGHEST: int
PRI_HIGH: int
PRI_NORMAL: int
PRI_LOW: int
PRI_LOWEST: int
CVAR_ARCHIVE: int
CVAR_USERINFO: int
CVAR_SERVERINFO: int
CVAR_SYSTEMINFO: int
CVAR_INIT: int
CVAR_LATCH: int
CVAR_ROM: int
CVAR_USER_CREATED: int
CVAR_TEMP: int
CVAR_CHEAT: int
CVAR_NORESTART: int
PRIV_NONE: int
PRIV_MOD: int
PRIV_ADMIN: int
PRIV_ROOT: int
PRIV_BANNED: int
CS_FREE: int
CS_ZOMBIE: int
CS_CONNECTED: int
CS_PRIMED: int
CS_ACTIVE: int
SS_DEAD: int
SS_LOADING: int
SS_GAME: int
TEAM_FREE: int
TEAM_RED: int
TEAM_BLUE: int
TEAM_SPECTATOR: int
WP_GAUNTLET: int
WP_MACHINEGUN: int
WP_SHOTGUN: int
WP_GRENADE_LAUNCHER: int
WP_ROCKET_LAUNCHER: int
WP_LIGHTNING: int
WP_RAILGUN: int
WP_PLASMAGUN: int
WP_BFG: int
WP_GRAPPLING_HOOK: int
WP_NAILGUN: int
WP_PROX_LAUNCHER: int
WP_CHAINGUN: int
WP_HMG: int
WP_HANDS: int
MAX_GENTITIES: int
ET_GENERAL: int
ET_PLAYER: int
ET_ITEM: int
ET_MISSILE: int
ET_MOVER: int
ET_BEAM: int
ET_PORTAL: int
ET_SPEAKER: int
ET_PUSH_TRIGGER: int
ET_TELEPORT_TRIGGER: int
ET_INVISIBLE: int
ET_GRAPPLE: int
ET_TEAM: int
ET_EVENTS: int
SVF_NOCLIENT: int
SVF_CLIENTMASK: int
SVF_BOT: int
SVF_BROADCAST: int
SVF_PORTAL: int
SVF_USE_CURRENT_ORIGIN: int
SVF_SINGLECLIENT: int
SVF_NOSERVERINFO: int
SVF_CAPSULE: int
SVF_NOTSINGLECLIENT: int
FL_GODMODE: int
FL_NOTARGET: int
FL_TEAMSLAVE: int
FL_NO_KNOCKBACK: int
FL_DROPPED_ITEM: int
FL_NO_BOTS: int
FL_NO_HUMANS: int
FL_FORCE_GESTURE: int
EF_DEAD: int
EF_TICKING: int
EF_TELEPORT_BIT: int
EF_AWARD_EXCELLENT: int
EF_PLAYER_EVENT: int
EF_BOUNCE: int
EF_BOUNCE_HALF: int
EF_AWARD_GAUNTLET: int
EF_NODRAW: int
EF_FIRING: int
EF_KAMIKAZE: int
EF_MOVER_STOP: int
EF_AWARD_CAP: int
EF_TALK: int
EF_CONNECTION: int
EF_VOTED: int
EF_AWARD_IMPRESSIVE: int
EF_AWARD_DEFEND: int
EF_AWARD_ASSIST: int
EF_AWARD_DENIED: int
EF_TEAMVOTED: int
STAT_HEALTH: int
STAT_HOLDABLE_ITEM: int
STAT_RUNE: int
STAT_WEAPONS: int
STAT_ARMOR: int
STAT_BSKILL: int
STAT_CLIENTS_READY: int
STAT_MAX_HEALTH: int
STAT_SPINUP: int
STAT_FLIGHT_THRUST: int
STAT_MAX_FLIGHT_FUEL: int
STAT_CUR_FLIGHT_FUEL: int
STAT_FLIGHT_REFUEL: int
STAT_QUADKILLS: int
STAT_ARMORTYPE: int
STAT_KEY: int
STAT_OTHER_HEALTH: int
STAT_OTHER_ARMOR: int
PERS_ROUND_SCORE: int
PERS_COMBOKILL_COUNT: int
PERS_RAMPAGE_COUNT: int
PERS_MIDAIR_COUNT: int
PERS_REVENGE_COUNT: int
PERS_PERFORATED_COUNT: int
PERS_HEADSHOT_COUNT: int
PERS_ACCURACY_COUNT: int
PERS_QUADGOD_COUNT: int
PERS_FIRSTFRAG_COUNT: int
PERS_PERFECT_COUNT: int
PW_REDFLAG: int
PW_BLUEFLAG: int
PW_NEUTRALFLAG: int
PW_QUAD: int
PW_BATTLESUIT: int
PW_HASTE: int
PW_INVIS: int
PW_REGEN: int
PW_FLIGHT: int
PW_INVULNERABILITY: int
PW_FREEZE: int
KEY_SILVER: int
KEY_GOLD: int
KEY_MASTER: int
MOVER_POS1: int
MOVER_POS2: int
MOVER_1TO2: int
MOVER_2TO1: int
TR_STATIONARY: int
TR_INTERPOLATE: int
TR_LINEAR: int
TR_LINEAR_STOP: int
TR_SINE: int
TR_GRAVITY: int
TR_CUSTOM_GRAVITY: int
SAY_ALL: int
SAY_TEAM: int
SAY_TELL: int
DAMAGE_RADIUS: int
DAMAGE_NO_ARMOR: int
DAMAGE_NO_KNOCKBACK: int
DAMAGE_NO_PROTECTION: int
DAMAGE_NO_TEAM_PROTECTION: int
MOD_UNKNOWN: int
MOD_SHOTGUN: int
MOD_GAUNTLET: int
MOD_MACHINEGUN: int
MOD_GRENADE: int
MOD_GRENADE_SPLASH: int
MOD_ROCKET: int
MOD_ROCKET_SPLASH: int
MOD_PLASMA: int
MOD_PLASMA_SPLASH: int
MOD_RAILGUN: int
MOD_LIGHTNING: int
MOD_BFG: int
MOD_BFG_SPLASH: int
MOD_WATER: int
MOD_SLIME: int
MOD_LAVA: int
MOD_CRUSH: int
MOD_TELEFRAG: int
MOD_FALLING: int
MOD_SUICIDE: int
MOD_TARGET_LASER: int
MOD_TRIGGER_HURT: int
MOD_NAIL: int
MOD_CHAINGUN: int
MOD_PROXIMITY_MINE: int
MOD_KAMIKAZE: int
MOD_JUICED: int
MOD_GRAPPLE: int
MOD_SWITCH_TEAMS: int
MOD_THAW: int
MOD_LIGHTNING_DISCHARGE: int
MOD_HMG: int
MOD_RAILGUN_HEADSHOT: int
EV_FOOTSTEP: int
EV_FOOTSTEP_METAL: int
EV_FOOTSPLASH: int
EV_FOOTWADE: int
EV_SWIM: int
EV_FALL_SHORT: int
EV_FALL_MEDIUM: int
EV_FALL_FAR: int
EV_JUMP_PAD: int
EV_JUMP: int
EV_WATER_TOUCH: int
EV_WATER_LEAVE: int
EV_WATER_UNDER: int
EV_WATER_CLEAR: int
EV_ITEM_PICKUP: int
EV_GLOBAL_ITEM_PICKUP: int
EV_NOAMMO: int
EV_CHANGE_WEAPON: int
EV_DROP_WEAPON: int
EV_FIRE_WEAPON: int
EV_USE_ITEM0: int
EV_USE_ITEM1: int
EV_USE_ITEM2: int
EV_USE_ITEM3: int
EV_USE_ITEM4: int
EV_USE_ITEM5: int
EV_USE_ITEM6: int
EV_USE_ITEM7: int
EV_USE_ITEM8: int
EV_USE_ITEM9: int
EV_USE_ITEM10: int
EV_USE_ITEM11: int
EV_USE_ITEM12: int
EV_USE_ITEM13: int
EV_USE_ITEM14: int
EV_USE_ITEM15: int
EV_ITEM_RESPAWN: int
EV_ITEM_POP: int
EV_PLAYER_TELEPORT_IN: int
EV_PLAYER_TELEPORT_OUT: int
EV_GRENADE_BOUNCE: int
EV_GENERAL_SOUND: int
EV_GLOBAL_SOUND: int
EV_GLOBAL_TEAM_SOUND: int
EV_BULLET_HIT_FLESH: int
EV_BULLET_HIT_WALL: int
EV_MISSILE_HIT: int
EV_MISSILE_MISS: int
EV_MISSILE_MISS_METAL: int
EV_RAILTRAIL: int
EV_SHOTGUN: int
EV_BULLET: int
EV_PAIN: int
EV_DEATH1: int
EV_DEATH2: int
EV_DEATH3: int
EV_DROWN: int
EV_OBITUARY: int
EV_POWERUP_QUAD: int
EV_POWERUP_BATTLESUIT: int
EV_POWERUP_REGEN: int
EV_POWERUP_ARMORREGEN: int
EV_GIB_PLAYER: int
EV_SCOREPLUM: int
EV_PROXIMITY_MINE_STICK: int
EV_PROXIMITY_MINE_TRIGGER: int
EV_KAMIKAZE: int
EV_OBELISKEXPLODE: int
EV_OBELISKPAIN: int
EV_INVUL_IMPACT: int
EV_JUICED: int
EV_LIGHTNINGBOLT: int
EV_DEBUG_LINE: int
EV_TAUNT: int
EV_TAUNT_YES: int
EV_TAUNT_NO: int
EV_TAUNT_FOLLOWME: int
EV_TAUNT_GETFLAG: int
EV_TAUNT_GUARDBASE: int
EV_TAUNT_PATROL: int
EV_FOOTSTEP_SNOW: int
EV_FOOTSTEP_WOOD: int
EV_ITEM_PICKUP_SPEC: int
EV_OVERTIME: int
EV_GAMEOVER: int
EV_MISSILE_MISS_DMGTHROUGH: int
EV_THAW_PLAYER: int
EV_THAW_TICK: int
EV_SHOTGUN_KILL: int
EV_POI: int
EV_DEBUG_HITBOX: int
EV_LIGHTNING_DISCHARGE: int
EV_RACE_START: int
EV_RACE_CHECKPOINT: int
EV_RACE_FINISH: int
EV_DAMAGEPLUM: int
EV_AWARD: int
EV_INFECTED: int
EV_NEW_HIGH_SCORE: int
MAX_CLIENTS: int
MAX_CONFIGSTRINGS: int
CS_SERVERINFO: int
CS_SYSTEMINFO: int
CS_MUSIC: int
CS_MESSAGE: int
CS_MOTD: int
CS_WARMUP: int
CS_SCORES1: int
CS_SCORES2: int
CS_VOTE_TIME: int
CS_VOTE_STRING: int
CS_VOTE_YES: int
CS_VOTE_NO: int
CS_GAME_VERSION: int
CS_LEVEL_START_TIME: int
CS_INTERMISSION: int
CS_ITEMS: int
CS_BOTINFO: int
CS_MODELS: int
CS_SOUNDS: int
CS_PLAYERS: int
CS_LOCATIONS: int
CS_LAST_GENERIC: int
CS_FLAGSTATUS: int
CS_SCORES1PLAYER: int
CS_SCORES2PLAYER: int
CS_ROUND_WARMUP: int
CS_ROUND_START_TIME: int
CS_TEAMCOUNT_RED: int
CS_TEAMCOUNT_BLUE: int
CS_SHADERSTATE: int
CS_NEXTMAP: int
CS_PRACTICE: int
CS_FREECAM: int
CS_PAUSE_START_TIME: int
CS_PAUSE_END_TIME: int
CS_TIMEOUTS_RED: int
CS_TIMEOUTS_BLUE: int
CS_MODEL_OVERRIDE: int
CS_PLAYER_CYLINDERS: int
CS_DEBUGFLAGS: int
CS_ENABLEBREATH: int
CS_DMGTHROUGHDEPTH: int
CS_AUTHOR: int
CS_AUTHOR2: int
CS_ADVERT_DELAY: int
CS_PMOVEINFO: int
CS_ARMORINFO: int
CS_WEAPONINFO: int
CS_PLAYERINFO: int
CS_SCORE1STPLAYER: int
CS_SCORE2NDPLAYER: int
CS_CLIENTNUM1STPLAYER: int
CS_CLIENTNUM2NDPLAYER: int
CS_ATMOSEFFECT: int
CS_MOST_DAMAGEDEALT_PLYR: int
CS_MOST_ACCURATE_PLYR: int
CS_REDTEAMBASE: int
CS_BLUETEAMBASE: int
CS_BEST_ITEMCONTROL_PLYR: int
CS_MOST_VALUABLE_OFFENSIVE_PLYR: int
CS_MOST_VALUABLE_DEFENSIVE_PLYR: int
CS_MOST_VALUABLE_PLYR: int
CS_GENERIC_COUNT_RED: int
CS_GENERIC_COUNT_BLUE: int
CS_AD_SCORES: int
CS_ROUND_WINNER: int
CS_CUSTOM_SETTINGS: int
CS_ROTATIONMAPS: int
CS_ROTATIONVOTES: int
CS_DISABLE_VOTE_UI: int
CS_ALLREADY_TIME: int
CS_INFECTED_SURVIVOR_MINSPEED: int
CS_RACE_POINTS: int
CS_DISABLE_LOADOUT: int
CS_MATCH_GUID: int
CS_STARTING_WEAPONS: int
CS_STEAM_ID: int
CS_STEAM_WORKSHOP_IDS: int
CS_MAX: int
MODELINDEX_ARMORSHARD: int
MODELINDEX_ARMORYELLOW: int
MODELINDEX_ARMORRED: int
MODELINDEX_ARMORGREEN: int
MODELINDEX_HEALTH5: int
MODELINDEX_HEALTH25: int
MODELINDEX_HEALTH50: int
MODELINDEX_HEALTHMEGA: int
MODELINDEX_GAUNTLET: int
MODELINDEX_SHOTGUN: int
MODELINDEX_MACHINEGUN: int
MODELINDEX_GRENADELAUNCHER: int
MODELINDEX_ROCKETLAUNCHER: int
MODELINDEX_LIGHTNING: int
MODELINDEX_RAILGUN: int
MODELINDEX_PLASMAGUN: int
MODELINDEX_BFG10K: int
MODELINDEX_GRAPPLINGHOOK: int
MODELINDEX_SHELLS: int
MODELINDEX_BULLETS: int
MODELINDEX_GRENADES: int
MODELINDEX_CELLS: int
MODELINDEX_LIGHTNINGAMMO: int
MODELINDEX_ROCKETS: int
MODELINDEX_SLUGS: int
MODELINDEX_BFGAMMO: int
MODELINDEX_TELEPORTER: int
MODELINDEX_MEDKIT: int
MODELINDEX_QUADDAMAGE: int
MODELINDEX_BATTLESUIT: int
MODELINDEX_HASTE: int
MODELINDEX_INVISIBILITY: int
MODELINDEX_REGENERATION: int
MODELINDEX_FLIGHT: int
MODELINDEX_REDFLAG: int
MODELINDEX_BLUEFLAG: int
MODELINDEX_KAMIKAZE: int
MODELINDEX_PORTAL: int
MODELINDEX_INVULNERABILITY: int
MODELINDEX_NAILS: int
MODELINDEX_MINES: int
MODELINDEX_BELT: int
MODELINDEX_SCOUT: int
MODELINDEX_GUARD: int
MODELINDEX_DAMAGE: int
MODELINDEX_AMMOREGEN: int
MODELINDEX_DOMINATIONPOINT: int
MODELINDEX_REDSKULL: int
MODELINDEX_BLUESKULL: int
MODELINDEX_NAILGUN: int
MODELINDEX_PROXLAUNCHER: int
MODELINDEX_CHAINGUN: int
MODELINDEX_SPAWNARMOR: int
MODELINDEX_HEAVYMACHINEGUN: int
MODELINDEX_HEAVYBULLETS: int
MODELINDEX_AMMOPACK: int
MODELINDEX_KEYSILVER: int
MODELINDEX_KEYGOLD: int
MODELINDEX_KEYMASTER: int
